### ISSUE TITLE
REPOSITOS MAVEN DESAPARECIDOS

### ISSUE THREAD

**Issue by yeyoext** [ctt-gob-es/clienteafirma#129]
bueno, esto es inaudito, los reposidos xades de maven estan borrados, señores, uatedes diran como hacemos....

**Comment by Gamuci** [comment]
Hola @yeyoext,

Aclara la cuestión un poco más, por favor.

El módulo de XAdES del Cliente sigue donde siempre (afirma-crypto-xades) y si te refieres a la biblioteca de XAdES que utiliza ([JXAdES](https://search.maven.org/search?q=jxades)), también. Justo ahora estamos colaborando con unos cambios en esta biblioteca. Quizás te hayas encontrado con alguna referencia a una versión SNAPSHOT que no esté publicada y de ahí venga el problema.

**Comment by yeyoext** [comment]
ya mande varios tikets de soporte a MHAP Incidencias, y no se han dignado a responder, llevo 1 mes pegandome para poder instalar el servicio de firma digital en el servidor, puede hacer funcionar el servicio "Aparentemente" modificando los repositos manualmente, firmar firmo, pero la firma no es valida, cuando firmo con el cliente autofirma (aplicacion de escritorio) un xml con XADES la firma la hace correcta, pero cuando firmo via tomcat la firma no es valida. 

No logoro entender que en la misma web del ministerio suban unos archivos que no funcionan, si dispones de afirma-server-triphase-signer.war que funcione me gustaria que me lo pasaras, puesto que los otros dos retriever y storage aparentemente funcionan.

Por cierto acabo de descargar nuevamente los repositos enteros, y sigo sin comprender porque publicais cosas que no funcionan de momento esto.........

Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building afirma-server-triphase-signer 1.7-SNAPSHOT
------------------------------------------------------------------------
The POM for es.gob.afirma:afirma-server-triphase-signer-core:jar:1.7-SNAPSHOT is missing, no dependency information available
The POM for es.gob.afirma:afirma-server-triphase-signer-document:jar:1.7-SNAPSHOT is missing, no dependency information available
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 0.418s
Finished at: Tue May 05 19:04:33 CEST 2020
Final Memory: 4M/15M
------------------------------------------------------------------------
Failed to execute goal on project afirma-server-triphase-signer: Could not resolve dependencies for project es.gob.afirma:afirma-server-triphase-signer:war:1.7-SNAPSHOT: The following artifacts could not be resolved: es.gob.afirma:afirma-server-triphase-signer-core:jar:1.7-SNAPSHOT, es.gob.afirma:afirma-server-triphase-signer-document:jar:1.7-SNAPSHOT: Could not find artifact es.gob.afirma:afirma-server-triphase-signer-core:jar:1.7-SNAPSHOT -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:

**Comment by yeyoext** [comment]
ahh, por cierto la ruta de esta dependencia nos encontramos que dentro del reposito https://repo.maven.apache.org/maven2/net/java/ no existe ninguna carpeta “xades\jxades\0.1.5\” donde obtener el archivo necesario.

**Comment by yeyoext** [comment]
y mas https://repo.maven.apache.org/maven2/es/gob/afirma/lib/afirma-lib-itext/ donde esta la libreria 1.3 que haceis referencia en el afirma-server-triphase-signer -> es/gob/afirma/lib/afirma-lib-itext/1.3-SNAPSHOT/afirma-lib-itext-1.3-SNAPSHOT.jar

así es imposible, no hay unos fuentes fiables para instalar y listo? no entiendo como esto funciona como funciona, aparte soporte 0 documentacion poca y mal.

**Comment by yeyoext** [comment]
@Gamuci ahi tienes varios.... y no sigo con mas porque ya me pierdo

**Comment by Gamuci** [comment]
Hola @yeyoext, 

Estás compilando una versión SNAPSHOT que apunta a versiones SNAPSHOT de otros proyectos, por eso los artefactos no están publicados en los repositorios de Maven.

Descárgate y compila con Maven los siguientes repositorios. Ahí está la versión de iText y otros tantos módulos que necesitas:

https://github.com/ctt-gob-es/clienteafirma-external
https://github.com/ctt-gob-es/jmulticard

Después compila todos los módulos del Cliente @firma (haz el "mvn clean install" en el directorio padre):

https://github.com/ctt-gob-es/clienteafirma

Con eso ya tendrás todas las dependencias que necesitas. Por último, entra en el módulo del servidor trifásico ("afirma-server-triphase-signer") de ese mismo repositorio y empaquétalo también.

Comenta cualquier problema que te surja. Nos interesa simplificar el que la gente pueda generar los artefactos del proyecto y colaborar, pero no podemos mandar a publicar una nueva versión de cada biblioteca después de cada cambio.

**Comment by yeyoext** [comment]
@Gamuci 
lo que simplemente necesito son los 3 componentes.

server-triphase-signer
server-retriever
server-storage

No se se java, no entiendo que me quieres decir que compile con maven los repositos de itext.

Nadie os pide que cada cambio publiqueis nada. lo que os pide es que publiqueis versiones "Estables" y versiones "beta", y sobre las betas hagais los cambios que querais porque ahora mismo no puedo compilar lo unico que necesito que funcione que es server-triphase-signer.

Lo que no se puede es facilitar a los integradores sistemas en webs oficiales del estado español algo que NO FUNCIONA ya que los war que publica la web NO FUNCIONAN
https://administracionelectronica.gob.es/ctt/clienteafirma/descargas
Servicios

Servicios desplegables junto al Miniapplet y Autofirma

afirma-server-triphase-signer_v2.9 (6677  KB · ZIP)iconoFecha de modificación: 10/05/2019
afirma-signature-retriever_v1.2 (8  KB · ZIP)iconoFecha de modificación: 22/01/2018
afirma-signature-storage_v1.4 (7  KB · ZIP)iconoFecha de modificación: 22/01/2018

**Comment by Gamuci** [comment]
Hola @yeyoext ,

Si eres un integrador, entonces hiciste bien en abrir la incidencia contra el servicio del ministerio. Es ahí donde deben atender tu incidencia.

En cualquier caso, acabo de descargarme el servicio trifásico desde la web que indicas, lo he desplegado en un Tomcat y he hecho pruebas de firmas trifásicas CAdES, XAdES y PAdES. Ha funcionado bien en todos los casos.

Es posible que haya algún problema en tu entorno. Asegúrate de enviar en la incidencia toda la información sobre tu entorno, el error que devuelve y los parámetros de configuración de firma que utilizas.

**Comment by yeyoext** [comment]
pues el error que me genera a mi es el Saf_26 y en los log del servidor me encuentro que hay una excepcion en el archivo afirma-server-triphase-signer

**Comment by clawgrip** [comment]
Hola,
 ¿Podrías por favor indicar versión de servidor de aplicaciones, versión de Java y copiar el texto de excepción?

¡Gracias!

**Comment by yeyoext** [comment]
GRAVE: No puedo procesar la entrada de Jar [module-info.class] desde el Jar [jar:file:/C:/xampp/tomcat/webapps/afirma-server-triphase-signer/WEB-INF/lib/jaxb-api-2.4.0-b180830.0359.jar!/] para las anotaciones
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:55)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:175)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:83)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2071)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1947)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1913)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1898)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5380)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1879)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by yeyoext** [comment]
C:\Users\programacion>java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)

**Comment by yeyoext** [comment]
@Gamuci ves que genera errores, te apresuraste a cerrar.

**Comment by yeyoext** [comment]
> Hola,
> ¿Podrías por favor indicar versión de servidor de aplicaciones, versión de Java y copiar el texto de excepción?
> 
> ¡Gracias!

GRAVE: No puedo procesar la entrada de Jar [module-info.class] desde el Jar [jar:file:/C:/xampp/tomcat/webapps/afirma-server-triphase-signer/WEB-INF/lib/jaxb-api-2.4.0-b180830.0359.jar!/] para las anotaciones
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
at org.apache.tomcat.util.bcel.classfile.ConstantPool.(ConstantPool.java:55)
at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:175)
at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:83)
at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2071)
at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1947)
at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1913)
at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1898)
at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5380)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1879)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

C:\Users\programacion>java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)

**Comment by clawgrip** [comment]
¿Qué versión de Tomcat?

**Comment by yeyoext** [comment]
@clawgrip Apache Tomcat/7.0.56

**Comment by clawgrip** [comment]
Tenía exactamente el mismo problema, y se solucionó al actualizar a un Tomcat más moderno.
Parece ser un asunto arreglado en Tomcat 7.0.103 (en mi caso puse una versión 8 de las últimas, con lo que no he probado la 103).
Si pruebas con la 103, te agradecería que compartieses los resultados aquí.
¡Gracias!

**Comment by yeyoext** [comment]
@clawgrip con Apache Tomcat/9.0.34

06-May-2020 18:43:07.550 GRAVE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Excepción de reserva de espacio para servlet [BatchPresigner]
	java.io.IOException: No se encuentra el fichero de configuracion del servicio: config.properties
		at es.gob.afirma.signers.batch.server.BatchPresigner.<clinit>(BatchPresigner.java:86)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:151)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1042)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)

**Comment by yeyoext** [comment]
@clawgrip me he puesto a indagar y ¡SORPRESA!, esta gente esta buscando archivos con unos nombres que no son los reales en los war, una vez cambiado los nombres el servicio funciona, bueno funciona... me hace la misma gracia que antes, genera una firma que no la reconoce nadie.

esta es la respuesta de una firma, que supuestamente mando el texto a firmar en base64 "UG9zdFVybD1odHRwOi8vMTkyLjE2OC4wLjIzNy9maXJtYQpQb3N0UGFyYW1OYW1lPXhtbA==", bien me hace una firma incorrecta y en vez de firmar el texto normal, me firma el base64, es increible.....

<?xml version="1.0" encoding="UTF-8"?>
<ds:Signature Id="Signature-d8d03a5f-13c1-4601-adc1-e6d113549c8e-Signature" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference Id="Reference-a4e46b9f-9b8c-40f7-967c-2000ee0858ce" Type="http://www.w3.org/2000/09/xmldsig#Object" URI="#Object-1ceea893-c4c2-4eda-98e9-4c1fe619f627"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#base64"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/><ds:DigestValue>lrLJ7MDSFjikZEWbD3nk5jumijA2KRF96dWB7fymIk8WL7SwFfdSOo+nRRLX9SvCt09oRlPaxmSJ&#xd;
21XWmwBERA==</ds:DigestValue></ds:Reference><ds:Reference Type="http://uri.etsi.org/01903#SignedProperties" URI="#Signature-d8d03a5f-13c1-4601-adc1-e6d113549c8e-SignedProperties"><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/><ds:DigestValue>57zr0Ocj2utncWkc0LQnfIx+Efa2cJFVuDtLNeQmpPbibuHGWyegYiDyci474G/jqkY9v1DqKK3Q&#xd;
K8NJHnRb7g==</ds:DigestValue></ds:Reference><ds:Reference URI="#Signature-d8d03a5f-13c1-4601-adc1-e6d113549c8e-KeyInfo"><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/><ds:DigestValue>K5JGpg/JeSQDsLVZLabttzA9r2WEWW27WnrZ3jAO1F89Ww6BKd0KpWRLUFEPJ5iBs6LNGVgSK2Jp&#xd;
Qj1yRCdq/A==</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue Id="Signature-d8d03a5f-13c1-4601-adc1-e6d113549c8e-SignatureValue">avBrzcztagqtr4e5I/aH+Jk/4VFbTZhcLlBKwGEOha57U35zpqENdhXjpHwDpVDCUkSRDe1W5enT&#xd;
IhP2oWhdV3gwU2rEYqsNPg8RpBLC8cimsAwD//8bWgcjOFv4rqbBNr3yBsG6mg+VwydXoxWDM9OZ&#xd;
yQkN7VP/dJuvNfF+BXBhUdlwRmtM6Bgg6c30yeI22si954Q5CJ8+vGH8gfA1JHBVnuFLbaGWFI4B&#xd;
OGmbHKJWcZvoJW0SHCcNZrm8ZlIsHeLFUXUfeZ8V9+cfHd1yYIVO/oUrSafNWgNepS49M9qX0SLQ&#xd;
5PuzD/scroApeG6wg55WgI6RsqEkJlIMLGPDbQ==</ds:SignatureValue><ds:KeyInfo Id="Signature-d8d03a5f-13c1-4601-adc1-e6d113549c8e-KeyInfo"><ds:X509Data><ds:X509Certificate>MIIGoDCCBYigAwIBAgIQB870ApMpi8VXrFmHwWyZSjANBgkqhkiG9w0BAQsFADBLMQswCQYDVQQG&#xd;
EwJFUzERMA8GA1UECgwIRk5NVC1SQ00xDjAMBgNVBAsMBUNlcmVzMRkwFwYDVQQDDBBBQyBGTk1U&#xd;
IFVzdWFyaW9zMB4XDTE2MDgxMTEwNTUwMloXDTIwMDgxMTEwNTUwMloweTELMAkGA1UEBhMCRVMx&#xd;
EjAQBgNVBAUTCTA5MTk3NjQ3UTEZMBcGA1UEBAwQQkFSUkFHQU4gQkVOSVRFWjEOMAwGA1UEKgwF&#xd;
QkVMRU4xKzApBgNVBAMMIkJBUlJBR0FOIEJFTklURVogQkVMRU4gLSAwOTE5NzY0N1EwggEiMA0G&#xd;
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDA/ki7Lz40wUmhzQ9K+UMWrOvxwsHyPjjuUGQ6T8b+&#xd;
dmN7lh2jT3V733X+B0kK9l6Y8ER1dXbXJLIRHpJjQU1/+1oN9BNIku9ElwoyV56gxyX2ePkFOTK2&#xd;
usd9PPtQ69fLmWSz4CsKiRiJQKCDSfF0kWjrk4zYuulirOFyyPtjjpASVvoDiAg6lP8nsmWmCZpj&#xd;
unaRY67FOaDrjB2LwQDyUmgvubkRrXjDxU1UKno5ymKhXJgPz1WlZo9eqdMdwJt45Kq+hscL51gp&#xd;
qQsxAueRKweYjteNv/62caBYyhjJkk3A/XabQqhAuhLpM7ZlSsNNUsSe8484fd5WLq7mCExXAgMB&#xd;
AAGjggNQMIIDTDCBgwYDVR0RBHwweoETdGVzZm9yYUBob3RtYWlsLmNvbaRjMGExGDAWBgkrBgEE&#xd;
AaxmAQQMCTA5MTk3NjQ3UTEWMBQGCSsGAQQBrGYBAwwHQkVOSVRFWjEXMBUGCSsGAQQBrGYBAgwI&#xd;
QkFSUkFHQU4xFDASBgkrBgEEAaxmAQEMBUJFTEVOMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQD&#xd;
AgXgMCMGA1UdJQQcMBoGCCsGAQUFBwMEBggrBgEFBQcDAgYEVR0lADAdBgNVHQ4EFgQUvF6gSVa+&#xd;
bv4jJAyGeGZfvu7KiQ4wHwYDVR0jBBgwFoAUsdRPxCN5+kQFCcbrOc/oNbC4IGQwgYIGCCsGAQUF&#xd;
BwEBBHYwdDA9BggrBgEFBQcwAYYxaHR0cDovL29jc3B1c3UuY2VydC5mbm10LmVzL29jc3B1c3Uv&#xd;
T2NzcFJlc3BvbmRlcjAzBggrBgEFBQcwAoYnaHR0cDovL3d3dy5jZXJ0LmZubXQuZXMvY2VydHMv&#xd;
QUNVU1UuY3J0MIHdBgNVHSAEgdUwgdIwgc8GCisGAQQBrGYDCgEwgcAwKQYIKwYBBQUHAgEWHWh0&#xd;
dHA6Ly93d3cuY2VydC5mbm10LmVzL2RwY3MvMIGSBggrBgEFBQcCAjCBhQyBgkNlcnRpZmljYWRv&#xd;
IHJlY29ub2NpZG8uIFN1amV0byBhIGxhcyBjb25kaWNpb25lcyBkZSB1c28gZXhwdWVzdGFzIGVu&#xd;
IGxhIERQQyBkZSBsYSBGTk1ULVJDTSAoQy9Kb3JnZSBKdWFuIDEwNi0yODAwOS1NYWRyaWQtRXNw&#xd;
YcOxYSkwJQYIKwYBBQUHAQMEGTAXMAgGBgQAjkYBATALBgYEAI5GAQMCAQ8wgbQGA1UdHwSBrDCB&#xd;
qTCBpqCBo6CBoIaBnWxkYXA6Ly9sZGFwdXN1LmNlcnQuZm5tdC5lcy9jbj1DUkw3NDQsY249QUMl&#xd;
MjBGTk1UJTIwVXN1YXJpb3Msb3U9Q0VSRVMsbz1GTk1ULVJDTSxjPUVTP2NlcnRpZmljYXRlUmV2&#xd;
b2NhdGlvbkxpc3Q7YmluYXJ5P2Jhc2U/b2JqZWN0Y2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQw&#xd;
DQYJKoZIhvcNAQELBQADggEBABkLlwix/SmMFAnDRCIW5UmuyFw8dLEZUOi0wrXNxTigEyCU4KMj&#xd;
KnI6+EB2dsxPkd/VUSpv2sVLC//EpK2njMKLEHcjawW0Z8i1bIsleehWTgD7rBC0bWvSs89jxvVt&#xd;
vd2LBClrlPqr00ZzULlIshcDSuPsrrIeY+o8PUUWfgaGO1cSlPzKQWINqFq6R2+4FpG/WtjAhlU5&#xd;
Ms+MOo9djEHa8s1HB8NtocLGoZzgs03tUbleGFs/Tp83ycgvHtYIOvYiE09IQ0oa9o1vI8pmy/ZT&#xd;
/fniPkZzzYo6C7ISqBbFpirB1wkneZalp/PMbh0dks6CuNRXiLEqa2xp6vDVg+c=</ds:X509Certificate></ds:X509Data><ds:KeyValue><ds:RSAKeyValue><ds:Modulus>wP5Iuy8+NMFJoc0PSvlDFqzr8cLB8j447lBkOk/G/nZje5Ydo091e991/gdJCvZemPBEdXV21ySy&#xd;
ER6SY0FNf/taDfQTSJLvRJcKMleeoMcl9nj5BTkytrrHfTz7UOvXy5lks+ArCokYiUCgg0nxdJFo&#xd;
65OM2LrpYqzhcsj7Y46QElb6A4gIOpT/J7JlpgmaY7p2kWOuxTmg64wdi8EA8lJoL7m5Ea14w8VN&#xd;
VCp6OcpioVyYD89VpWaPXqnTHcCbeOSqvobHC+dYKakLMQLnkSsHmI7Xjb/+tnGgWMoYyZJNwP12&#xd;
m0KoQLoS6TO2ZUrDTVLEnvOPOH3eVi6u5ghMVw==</ds:Modulus><ds:Exponent>AQAB</ds:Exponent></ds:RSAKeyValue></ds:KeyValue></ds:KeyInfo><ds:Object Encoding="http://www.w3.org/2000/09/xmldsig#base64" Id="Object-1ceea893-c4c2-4eda-98e9-4c1fe619f627" MimeType="text/plain">UG9zdFVybD1odHRwOi8vMTkyLjE2OC4wLjIzNy9maXJtYQpQb3N0UGFyYW1OYW1lPXhtbA==</ds:Object><ds:Object><xades:QualifyingProperties Id="Signature-d8d03a5f-13c1-4601-adc1-e6d113549c8e-QualifyingProperties" Target="#Signature-d8d03a5f-13c1-4601-adc1-e6d113549c8e-Signature" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#"><xades:SignedProperties Id="Signature-d8d03a5f-13c1-4601-adc1-e6d113549c8e-SignedProperties"><xades:SignedSignatureProperties><xades:SigningTime>2020-05-06T19:08:05+02:00</xades:SigningTime><xades:SigningCertificate><xades:Cert><xades:CertDigest><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/><ds:DigestValue>zM7LtrmY+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/ksc+xxxxxxxxxxxxxxxxxxx==</ds:DigestValue></xades:CertDigest><xades:IssuerSerial><ds:X509IssuerName>CN=AC FNMT Usuarios, OU=Ceres, O=FNMT-RCM, C=ES</ds:X509IssuerName><ds:X509SerialNumber>xxxxxxxxxxxxxxxxxxxxxxxxxxxxx</ds:X509SerialNumber></xades:IssuerSerial></xades:Cert></xades:SigningCertificate></xades:SignedSignatureProperties><xades:SignedDataObjectProperties><xades:DataObjectFormat ObjectReference="#Reference-a4e46b9f-9b8c-40f7-967c-2000ee0858ce"><xades:Description/><xades:MimeType>text/plain</xades:MimeType><xades:Encoding>http://www.w3.org/2000/09/xmldsig#base64</xades:Encoding></xades:DataObjectFormat></xades:SignedDataObjectProperties></xades:SignedProperties></xades:QualifyingProperties></ds:Object></ds:Signature>
