### ISSUE TITLE
Cerramos las incidencias y dejamos al personal a la deriva

### ISSUE THREAD

**Issue by yeyoext** [ctt-gob-es/clienteafirma#130]
Hace un par de días abrí una incidencia, #129 y @Gamuci  la cerro, no antes sin decirme que todo lo publicado en https://administracionelectronica.gob.es/ctt/clienteafirma/descargas

> Servicios desplegables junto al Miniapplet y Autofirma
> 
> afirma-server-triphase-signer_v2.9 (6677 KB · ZIP)iconoFecha de modificación: 10/05/2019
> afirma-signature-retriever_v1.2 (8 KB · ZIP)iconoFecha de modificación: 22/01/2018
> afirma-signature-storage_v1.4 (7 KB · ZIP)iconoFecha de modificación: 22/01/2018

a el le funcionaba sin problemas, pues bien, a las pruebas me remito que no es así. tras actualizar lo siguiente:

Apache Tomcat/9.0.34

java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)

me encuentro con lo siguiente

> 06-May-2020 18:43:07.550 GRAVE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Excepción de reserva de espacio para servlet [BatchPresigner]
> java.io.IOException: No se encuentra el fichero de configuracion del servicio: config.properties
> at es.gob.afirma.signers.batch.server.BatchPresigner.(BatchPresigner.java:86)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:151)
> at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1042)
> at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
> at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
> at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> at java.lang.Thread.run(Thread.java:748)

y mi pregunta es para el Sr. @Gamuci, ¿Cómo es posible que a usted le funcione y a mi me diga que no se encuentran archivos?

Tras modificar el nombre de los archivos que en los desplegables se nombran configuration.properties para que no genere error y realice una firma y me encuentre con lo siguiente:

1.- Si en la configuración paso datos en BASE64 (un xml para firmar con XADES)  ¿Porque el cliente autofirma no firma los datos DECODIFICADOS?
2.- ¿Porque la firma resultante NO ES VALIDA?, ¿Porqué la firma resultante es totalmente diferente a la firma con la aplicacion de escritorio?

Se @Gamuci, no entiendo porque cierra los temas si de sobra sabe que NO ESTAN RESUELTOS.

Sin hablar del tema de los repositos que siguen desaparecidos como ayer le demostré.

Me parece indignante que esta aplicación no disponga de una versión "ESTABLE", pues todo son "TESTER" a los cuales nos tenemos que aventurar a instalar haber si salta la liebre y funciona.

Y lo más indignante de todo es que este proyecto depende del estado español, seamos de los pocos paises que no disponen de un standard de firma electronica y que para poder avanzar en este pais tengamos tantisismas trabas, Soporte oficial DESAPARECIDO, Telefonos de secretarías INEXISTENTES, Documentación PARCHEADA y un largo etc.

Sr. @Gamuci si a usted le ha funcionado todo bien, Cree una carpeta en el proyecto con WAR estables, para su despliege. Si, esos mismos archivos que a usted le funcionan a la perfección publiquelos, y simplifique la vida a la gente.

**Comment by Gamuci** [comment]
La versión estable de los binarios distribuibles es la que hay [publicada en el PAe](https://administracionelectronica.gob.es/ctt/clienteafirma/descargas#.XsZAH877RPY).

Sigo sin entender qué quieres decir con que los repositorios están desaparecidos. Las versiones estables de todos los artefactos están publicados en el [repositorio central de Maven](https://search.maven.org/search?q=es.gob.afirma). Ahí hay poco más que decir y por eso se cerró el tema.

Si no te funciona, tratemos de identificar el problema. Por favor, detalla qué prueba estás haciendo.

**Comment by yeyoext** [comment]
@Gamuci 

> La versión estable de los binarios distribuibles es la que hay publicada en el PAe.
Fallan, no encuentran rutas de archivos como ya te demostré con los log.

la prueba es muy simple, FIRMAR UN XML CON XADES, los errores los que ves arriba, creo que soy muy detallado en la exposición.

tu tienes unos war que funcionan al 100%, que firman y no dan fallos?, subelos y los pruebo.

**Comment by Gamuci** [comment]
Te dejo un enlace a una versión del [servidor trifásico](https://drive.google.com/open?id=1WmlQKL50UWEm33f4_Cbt_q_fNhskP244) con los últimos cambios y los ficheros de configuración. Es una versión sobre la que no se han hecho muchas pruebas, pero veamos si a ti te da problemas o no.

Tienes que desplegarla y pasarle al servidor de aplicaciones la variable de entorno "clienteafirma.config.path" con el directorio en el que se encuentren los ficheros de configuración. Por ejemplo:

-Dclienteafirma.config.path="C:/afirma/config"
