### ISSUE TITLE
Proporcionar una verificación de firmas por linea de comandos sin interfaz gráfica

### ISSUE THREAD

**Issue by maoterodapena** [ctt-gob-es/clienteafirma#132]
Actualmente se permite abrir un panel gráfico con la información de firmas en documentos con "AutoFirma verify -i <fichero>".

Creo que sería muy útil una opción sin necesidad de  interfaz, que mostrara la la información de las firmas en modo texto (a ser posible, en un formato fácilmente parseable)

**Comment by Gamuci** [comment]
Gracias @maoterodapena.

Quiero hacer hincapié en un tema. AutoFirma no valida las firmas. Tan sólo verifica que el valor de firma sea válido y avisa en caso de que los certificados estén caducados (comprobándolo usando la fecha que tenga configurada el usuario en su equipo). Para validar las firmas hay que utilizar alguna herramienta online que específica como [VALIDe](https://valide.redsara.es/valide/validarFirma/ejecutar.html;jsessionid=A7183C7C4FEB7D8956099894A0C925CA).

Más allá de eso, ¿qué información crees que es útil que se proporcione a través de línea de comandos?

**Comment by maoterodapena** [comment]
Creo que los mismos datos que salen con la opción verify serían suficientes. Una  linea por campo, separada por ";", por ejemplo. Algo como:
"FULANO DE TAL";"ENTIDAD CERTIFICADORA"
"MENGANO DE TAL":"OTRA ENTIDAD"

Una aclaración. Cuando dices que no valida las firmas, te refieres a que no se comprueba la revocación?

**Comment by Gamuci** [comment]
Exacto. No se comprueba la revocación de los certificados, ni tampoco se comprueba que los certificados hayan sido emitidos por autoridades de confianza.

**Comment by mgip** [comment]
Hola. Una pregunta, este hilo tiene que ver con esto?

[root@plesk opt]# autofirma verify -i test_signed.pdf 
Error no reconocido: No X11 DISPLAY variable was set, but this program performed an operation which requires it.

[root@plesk opt]# export DISPLAY=:0.0
[root@plesk opt]# autofirma verify -i test_signed.pdf 
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at es.gob.afirma.standalone.LookAndFeelManager.<clinit>(LookAndFeelManager.java:64)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549)
[root@plesk opt]# 


Muchas Gracias.
Una ultima pregunta, donde puedo encontrar la documentacion con ejemplo de como usar Autofirma por la lineas de comandos?

La documentacion se centra con GUI.

**Comment by mapascual** [comment]
Estoy de acuerdo en que esta opción sería muy útil.
