### ISSUE TITLE
No lista archivos cuando hay acentos en ficheros o carpetas.

### ISSUE THREAD

**Issue by aleixq** [ctt-gob-es/clienteafirma#144]
No lista archivos cuando hay acentos en ficheros o carpetas.

desde cli tira esto:
```
Exception in thread "Basic L&F File Loading Thread" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/suport3/M??sica
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at java.desktop/sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:247)
        at java.desktop/javax.swing.filechooser.FileSystemView.getFiles(FileSystemView.java:523)
        at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(BasicDirectoryModel.java:290)
        at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(BasicDirectoryModel.java:279)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
tirando así:
` export JAVA_OPTS="-Dsun.jnu.encoding=C -Dfile.encoding=C" && AutoFirma`
tampoco

ejecutado en linux mint y versión autofirma 1.6.5  .

**Comment by Gamuci** [comment]
Hola, @aleixq:

No hay referencia a AutoFirma en la excepción. ¿Puedes indicar qué comando u operación te falla?

Gracias.
