### ISSUE TITLE
Error FNMT con Fedora 32

### ISSUE THREAD

**Issue by graux** [ctt-gob-es/clienteafirma#168]
Después de hacer el "hack" de crear el enlace simbólico de:
`sudo ln -s /usr/lib64 /opt/firefox-`

No puedo realizar la firma de:
Solicitud de Certificado de Representante para Administradores Únicos y Solidarios

Al firmar desde Chrome/Firefox el journal me dice:
```
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.ProxyUtil clearJavaProxy
INFO: No se usara Proxy para las conexiones de red
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: No se buscaran nuevas versiones de la aplicacion
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFO: AutoFirma 1.6.5
Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 5.8.18-200.fc32.x86_64
Version de Java: 1.8.0_272
Arquitectura del JRE: 64
Java Vendor: Red Hat, Inc.
Localizacion por defecto: en_US
Tamano actual en memoria: 236MB
Tamano maximo de memoria: 3495MB
Memoria actualmente libre: 180MB
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Invocacion por protocolo con URL:
afirma://sign?fileid=XXXXXXXXXX&rtservlet=https%3A%2F%2Fapuc20.cert.fnmt.es%2Fafirma-signature-retriever%2FRetrieveService&key=XXXXX
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher launch
INFO: Se invoca a la aplicacion para realizar una operacion de firma/multifirma
Jan 13, 2021 1:02:29 PM es.gob.afirma.core.misc.protocol.ProtocolInvocationUriParser parserUri
INFO: URI recibida: afirma://sign?fileid=XXXXXXXXXXX&rtservlet=https%3A%2F%2Fapuc20.cert.fnmt.es%2Fafirma-signature-retriever%2FRetrieveService&key=XXXXX
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.protocol.ProtocolInvocationLauncherUtil getDataFromRetrieveServlet
INFO: Intentamos recuperar los datos del servidor con la URL:
https://apuc20.cert.fnmt.es/afirma-signature-retriever/RetrieveService?op=get&v=1_0&id=XXXXXXXXXXXXX
Jan 13, 2021 1:02:29 PM es.gob.afirma.core.misc.http.UrlHttpManagerImpl disableSslChecks
WARNING: Deshabilitadas comprobaciones SSL
Jan 13, 2021 1:02:29 PM es.gob.afirma.core.misc.http.UrlHttpManagerImpl enableSslChecks
INFO: Habilitadas comprobaciones SSL
Jan 13, 2021 1:02:29 PM es.gob.afirma.core.misc.http.DataDownloader downloadData
INFO: El contenido a obtener es Base64
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher launch
INFO: Se inicia la operacion de firma
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.mozilla.shared.SharedNssUtil getSharedUserProfileDirectory
INFO: Detectado directorio de perfil de NSS: ̴/.pki/nssdb
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFO: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib64/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='sql:/USERHOME/.pki/nssdb' certPrefix='' keyPrefix='' flags='readOnly'"
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFO: Proveedor PKCS#11 para NSS anadido para perfil compartido: SunPKCS11-NSSCrypto-AFirma
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado un DNIe: java.security.ProviderException: No se ha podido inicializar el proveedor de DNIe: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: Tarjeta FNMT-RCM CERES 4.30 o superior
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado una tarjeta CERES 4.30 o superior: java.security.ProviderException: No se ha podido inicializar el proveedor de Ceres 4.30 y superior: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: Tarjeta FNMT-RCM CERES
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado una tarjeta CERES: java.security.ProviderException: No se ha podido conectar con la tarjeta CERES: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFO: Se incluiran los modulos nativos de DNIe/CERES si se encuentran configurados
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFO: Obtenidos los modulos externos de Mozilla desde 'pkcs11.txt'
Jan 13, 2021 1:02:29 PM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
INFO: No se han encontrado modulos PKCS#11 externos instalados en Firefox
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.protocol.ProtocolInvocationLauncherSign processSign
INFO: Obtenido gestor de almacenes de claves: Gestor de almacenes de claves NSS con nombre NSS
Jan 13, 2021 1:02:29 PM es.gob.afirma.standalone.protocol.ProtocolInvocationLauncherSign processSign
INFO: Cargando dialogo de seleccion de certificados...
Jan 13, 2021 1:02:30 PM es.gob.afirma.ui.core.jse.JSEUIManager showCertificateSelectionDialog
SEVERE: Se genero un error en el dialogo de seleccion de certificados: java.lang.reflect.InvocationTargetException
Jan 13, 2021 1:02:30 PM es.gob.afirma.standalone.protocol.ProtocolInvocationLauncherSign processSign
SEVERE: Error al mostrar el dialogo de seleccion de certificados: java.awt.HeadlessException
Jan 13, 2021 1:02:30 PM es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher launch
SEVERE: Error en los parametros de firma: java.awt.HeadlessException
java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1763)
        at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1838)
        at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
        at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863)
        at es.gob.afirma.ui.core.jse.JSEUIManager.showErrorMessage(JSEUIManager.java:814)
        at es.gob.afirma.core.ui.AOUIFactory.showErrorMessage(AOUIFactory.java:211)
        at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncherErrorManager.showError(ProtocolInvocationLauncherErrorManager.java:117)
        at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncherErrorManager.showError(ProtocolInvocationLauncherErrorManager.java:108)
        at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncherSign.processSign(ProtocolInvocationLauncherSign.java:331)
        at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher.launch(ProtocolInvocationLauncher.java:429)
        at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher.launch(ProtocolInvocationLauncher.java:80)
        at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:616)
Comando no reconocido: afirma://sign?fileid=JmBeMpz1nAY32w8SGz0K&rtservlet=https%3A%2F%2Fapuc20.cert.fnmt.es%2Fafirma-signature-retriever%2FRetrieveService&key=43150598
Sintaxis: AutoFirma cmd [options...]
Comandos cmd:
  sign                 (firma de fichero)
  cosign         (cofirma de fichero)
  countersign         (contrafirma de fichero)
  listaliases         (lista los alias disponibles en el almacen)
  verify         (abre un panel con la informacion de validacion de una firma o certificado)
  batchsign         (firma/multifirma de lotes de ficheros)
  createdigest         (creacion de huella digitales con interfaz grafica)
  checkdigest         (comprobacion de huella digitales con interfaz grafica)
Utilice "AutoFirma cmd -help" para ver la sintaxis del comando "cmd"
```
Tengo instalado:
```
java-1.8.0-openjdk-headless-1.8.0.272.b10-0.fc32.x86_64
java-latest-openjdk-headless-15.0.1.9-9.rolling.fc32.x86_64
```

¿Alguna idea de cómo puedo continuar?
Gracias

**Comment by LucasFA** [comment]
#302
