### ISSUE TITLE
Re: Problemas con Autofirma en Linux, integración en el navegador

### ISSUE THREAD

**Issue by alexpdp7** [ctt-gob-es/clienteafirma#172]
Puedo usar Autofirma en mi sistema Linux para firmar archivos con mi DNIE sin problema.

También puedo usar mi DNIE en mi navegador Firefox para identificarme.

Sin embargo, la integración de Autofirma con el navegador no me funciona ni en Chrome ni en Firefox. Entiendo que Autofirma hace un bind a un puerto aleatorio y escucha peticiones HTTPS, y las webs que integran Autofirma hacen peticiones a este puerto para operar. Sin embargo, observo que estas peticiones fallan, al parecer porque el navegador no confía en el certificado que usa Autofirma para la comunicación HTTPS.

Veo mensajes como:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://127.0.0.1:54962/afirma. (Reason: CORS request did not succeed).
```

en mi navegador, existiendo un proceso:

```
java -jar /usr/lib/AutoFirma/AutoFirma.jar afirma://service?ports=54962,57670,51872&v=1&idsession=....
```

He intentado importar el certificado a mano sin demasiado éxito.

¿Pueden ayudarme a resolver este problema?

**Comment by juanjosepablos** [comment]
En Firefox. Asegúrate que tienes un solo perfil "/usr/bin/firefox -p" 
Con el Firefox cerrado. Ve a Autofirma > Herramientas > Restaurar instalación 
Ve a https://valide.redsara.es/valide/validarFirma/ejecutar.html para probar a firmar

**Comment by alexpdp7** [comment]
Excelente, ha funcionado!

Puede que esto esté en un FAQ y se me haya pasado, pero si no está documentado en ningún sitio, estaría interesante incluirlo.

**Comment by carlosnewmusic** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit at java.desktop/java.awt.Color.<clinit>(Color.java:275) at es.gob.afirma.standalone.LookAndFeelManager.<clinit>(LookAndFeelManager.java:60) at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549)

**Comment by juanjosepablos** [comment]
@carlosnewmusic ,
Esto no es un foro donde la gente viene a preguntar que hay de lo suyo. El error de @alexpdp7 es probable que fuera tener doble perfil en Firefox. Tu problema es que por alguna razón no encuentra la Libreria.
Quizas` export CLASSPATH=/usr/share/java/java-atk-wrapper.jar` podría solucionar tu problema. Pero parece mas un problema del sistema (Cosa que no proporcionas) que de autofirma en si.

**Comment by alwayswatchintv** [comment]
hola, tengo el mismo problema que alexpdp7, solo no tengo doble perfil ni masterpassword, tengo java 8....explico en #214 con mas detalle
gracias

**Comment by atomass** [comment]
> al iniciarlo desde "/usr/bin/AutoFirma"
> 
> Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit at java.desktop/java.awt.Color.(Color.java:275) at es.gob.afirma.standalone.LookAndFeelManager.(LookAndFeelManager.java:60) at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549)
> ![imagen](https://user-images.githubusercontent.com/19379457/108782098-44229680-756b-11eb-9b4e-026d8f8151da.png)
> 
> tengo el jre8-openjdk y el jdk11-openjdk
> Linux 5.10.15-1-MANJARO x86_64 GNU/Linux

Tuve el mismo problema y lo solucione' instalando Oracle JDK en lugar de OpenJDK

**Comment by t0mjoad** [comment]
Gracias @atomass por tu comentario, muy clarificador.

No como el tal  Juan Jose Pablos, un pedante que encima ayuda poco.

**Comment by juanjosepablos** [comment]
Deja de hacer el ridículo @t0mjoad ,  tus afinidades personales son de ámbito privado, si no tienes familia o amigos a los que comentarles estas cosas, mejor no lo hagas. Tu opinión sobre una persona aleatoria del planeta es irrelevante. A Internet se viene llorado de casa. Esto es un informe sobre "Autofirma Linux y navegadores web"

**Comment by t0mjoad** [comment]
sé perfectamente lo que es, una basura que usa software propietario de oracle en vez del openjdk, y con un creador mediocre que ningunea a la gente mientras no es ni siquiera capaz de generar documentación estandarizada. Te crees que eres Linus y eres más malo que el programador de Tizen.

**Comment by alexpdp7** [comment]
Por comentar esto antes de desuscribirme de este hilo

> En Firefox. Asegúrate que tienes un solo perfil "/usr/bin/firefox -p"
> Con el Firefox cerrado. Ve a Autofirma > Herramientas > Restaurar instalación
> Ve a https://valide.redsara.es/valide/firmar/ejecutar.html para probar a firmar

En este caso, mi problema no era de doble perfil, sino que se resolvía restaurando la instalación. Insisto que estaría bien documentar este proceso si no se puede mejorar de otra manera.

**Comment by juanjosepablos** [comment]
@alexpdp7 Yo creo que lo mejor es que cierres este informe. Si consideras que las FAQ están incompletas, ve a https://github.com/ctt-gob-es/clienteafirma/wiki/AutoFirma:-Problemas-en-la-instalaci%C3%B3n#por-qu%C3%A9-no-funciona-autofirma-con-firefox-reci%C3%A9n-instalado-o-con-mi-nuevo-perfil  Quizás se acepten los cambios.

 @t0mjoad Dado que tu comprensión lectora es limitada, me gustaría resumirte: 

**Internet es un lugar enorme donde puedes encontrar donde contar tus líos mentales**

- Esto es un simple informe de *Problemas con Autofirma en Linux, integración en el navegador* donde tus cosas  no interesan.
- Yo soy un simple usuario que ayudo a otro y **le funciono**
- Los demás usuarios lo ejecutan desde la linea de comandos. Eso es diferente a problema inicial.

**Comment by gopala410** [comment]
Joder, tengo fedora 33 y mi error es:
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/java.awt.Color.<clinit>(Color.java:275)
	at es.gob.afirma.standalone.LookAndFeelManager.<clinit>(LookAndFeelManager.java:60)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549)
Tened en cuenta que no soy experto en estas cacas de java y basurilla del gobierno que no explican como mierda se instala esto de principio a fin, si hay que hacer algo decidme por favor los pasos o de donde descargar las cosas o como mirar las cosas (version de java, directorio de instalacion)

**Comment by druizz90** [comment]
> Joder, tengo fedora 33 y mi error es: Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit at java.desktop/java.awt.Color.(Color.java:275) at es.gob.afirma.standalone.LookAndFeelManager.(LookAndFeelManager.java:60) at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549) Tened en cuenta que no soy experto en estas cacas de java y basurilla del gobierno que no explican como mierda se instala esto de principio a fin, si hay que hacer algo decidme por favor los pasos o de donde descargar las cosas o como mirar las cosas (version de java, directorio de instalacion)

Una solución que me funcionó en Fedora 34:

- Instalar la versión 8 del OpenJDK -> `sudo dnf install java-1.8.0-openjdk`
- Seleccionarla como versión por defecto -> `sudo update-alternatives --config java`

**Comment by gopala410** [comment]
> > Joder, tengo fedora 33 y mi error es: Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit at java.desktop/java.awt.Color.(Color.java:275) at es.gob.afirma.standalone.LookAndFeelManager.(LookAndFeelManager.java:60) at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549) Tened en cuenta que no soy experto en estas cacas de java y basurilla del gobierno que no explican como mierda se instala esto de principio a fin, si hay que hacer algo decidme por favor los pasos o de donde descargar las cosas o como mirar las cosas (version de java, directorio de instalacion)
> 
> Una solución que me funcionó en Fedora 34:
> 
>     * Instalar la versión 8 del OpenJDK -> `sudo dnf install java-1.8.0-openjdk`
> 
>     * Seleccionarla como versión por defecto -> `sudo update-alternatives --config java`

Muuuuchisimas gracias druizz90. Me ha funcionado tambien en fedora 33 a la perfeccion. Ahora si funciona la app esta d kk autofirma.
Me sorprende que este gobierno fascista y nazi no ponga en su web como instalarlo in LInux, solo en windows que es mas facil que mear, doble click siguiente siguiente ....

**Comment by gopala410** [comment]
Vuelvo a tener problemas con autofirma en fedora 33. 
me funciono durante unos meses pero ahora al ejecutarlo, no arranca dando el siguiente error:

autofirma 
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/java.awt.Color.<clinit>(Color.java:275)
	at es.gob.afirma.standalone.LookAndFeelManager.<clinit>(LookAndFeelManager.java:60)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549)

Que puedo hacer ? hay alguna forma de que esto funcione para siempre ? o tenemos que exiliarnos en un pais del primer mundo donde las cosas del estado funcionen y no haya mas funcionarios que ciudadanos decentes

**Comment by lbenitezm** [comment]
Buenos días,
Ayer abrí un comentario en otro hilo. Pero quizá el problema se describe mejor en este otro. Se encuentra en #16 .
El problema se resume en:

- Me funciona Autofirma correctamente desde la interfaz gráfica. Firmo documento son problemas con el lector de tarjeta y el DNIe.
- Firefox me reconoce también los certificados del DNIe
- Se verifica correctamente en la página de la FNMT: [https://www.sede.fnmt.gob.es/certificados/persona-fisica/verificar-estado](https://github.com/ctt-gob-es/clienteafirma/issues/url)
- Sin embargo falla al hacer la validación en la página de valide.redsara porque no abre el Autofirma desde FireFox [https://valide.redsara.es/valide/validarCertificado/ejecutar.html](https://github.com/ctt-gob-es/clienteafirma/issues/url)
- Y me da error al subir cosas al registro de la administración general del Estado en RedSara

La instalación que tengo es:

- Linux Mint 20.1 Ulyssa - 64 bits - 5.4.0-73-generic
- Java: java-8-openjdk-amd64
- Autofirma 1.7.1
- Firefox 100 - 64 bits (1 usuario. Certificados de DNIe de Autenticación y Firma. Autoridad: Autofirma ROOT


En el manual de Autofirma acabo de leer:

_**_NOTA**: Se han encontrado problemas de compatibilidad con el Firefox por defecto
instalado con el sistema operativo con el entorno KDE. En este caso, Firefox no
atiende las llamadas realizadas por la página para que abra la aplicación. Se
recomienda la instalación del Firefox oficial de la web de Mozilla.__

Pero no se si algo aplicable a mi -creo que mi Firefox no corre en KDE y es el oficial de la página de web de Firefox.

Las salidas de Autofirma en la consola están en el otro hilo.

Alguien se ha encontrado con este problema, ¿alguna pista? Gracias a todos !!

**Comment by lbenitezm** [comment]
> Buenos días, Ayer abrí un comentario en otro hilo. Pero quizá el problema se describe mejor en este otro. Se encuentra en #16 . El problema se resume en:
> 
> * Me funciona Autofirma correctamente desde la interfaz gráfica. Firmo documento son problemas con el lector de tarjeta y el DNIe.
> * Firefox me reconoce también los certificados del DNIe
> * Se verifica correctamente en la página de la FNMT: [https://www.sede.fnmt.gob.es/certificados/persona-fisica/verificar-estado](https://github.com/ctt-gob-es/clienteafirma/issues/url)
> * Sin embargo falla al hacer la validación en la página de valide.redsara porque no abre el Autofirma desde FireFox [https://valide.redsara.es/valide/validarCertificado/ejecutar.html](https://github.com/ctt-gob-es/clienteafirma/issues/url)
> * Y me da error al subir cosas al registro de la administración general del Estado en RedSara
> 
> La instalación que tengo es:
> 
> * Linux Mint 20.1 Ulyssa - 64 bits - 5.4.0-73-generic
> * Java: java-8-openjdk-amd64
> * Autofirma 1.7.1
> * Firefox 100 - 64 bits (1 usuario. Certificados de DNIe de Autenticación y Firma. Autoridad: Autofirma ROOT
> 
> En el manual de Autofirma acabo de leer:
> 
> _**_NOTA**: Se han encontrado problemas de compatibilidad con el Firefox por defecto instalado con el sistema operativo con el entorno KDE. En este caso, Firefox no atiende las llamadas realizadas por la página para que abra la aplicación. Se recomienda la instalación del Firefox oficial de la web de Mozilla.__
> 
> Pero no se si algo aplicable a mi -creo que mi Firefox no corre en KDE y es el oficial de la página de web de Firefox.
> 
> Las salidas de Autofirma en la consola están en el otro hilo.
> 
> Alguien se ha encontrado con este problema, ¿alguna pista? Gracias a todos !!

Problema solucionado. Lo podéis encontrar en el hilo: #16 al final del todo. Gracias por el soporte !!

**Comment by jahnog** [comment]
Algo para revisar es si Firefox está instalado en Ubuntu desde un **snap** o desde un paquete **deb**. Si esta instalado desde un snap hay que desinstalarlo
`sudo snap remove firefox`
e instalarlo desde un paquete deb
`sudo apt install firefox`
aunque esto solo es posible en Ubuntu en las versiones 21.10 o anteriores. La versión 22.04 solo tiene a Firefox disponible en snap.
El snap aísla mas a las aplicaciones (es mas seguro) pero también dificulta la comunicación del Navegador con otras aplicaciones y plugins.

**Comment by Vichman67** [comment]
Tras múltiples quebraderos de cabeza, os pongo aquí mi solución, totalmente funcional, para un entorno con Firefox, Ubuntu 22.04 y openjdk versión 11.0.16. 

No es necesario desinstalar el Firefox instalado en Ubuntu desde snap, pero con éste no funcionará AutoFirma. Pero podemos instalar un nuevo Firefox descargándolo desde https://ftp.mozilla.org/pub/firefox/releases/ y eligiendo allí una versión moderna, la platafor de 64-bit y el idioma que deseemos (por ejemplo "105.0. > linux-x86_64 > en-GB" para tener la versión 105 en inglés). Para instalar este Firefox, descargamos el fichero *.tar.bz2 y lo descomprimimos en un directorio al que podamos acceder(por ejemplo ~/Firefox/, creado por nosotros mismos). En ese directorio tendremos el ejecutable "firefox".

Pues bien, cerramos (si está abierto) el Firefox instalado desde snap y arrancamos el nuevo Firefox que acabamos de descargar. Éste debe tener sólo un perfil de usuario. Sobre este nuevo Firefox debemos instalar los certificados digitales personales que queramos utilizar, y hay que asegurarse de que el certificado de autoridades Autofirma ROOT está presente (si no habreá que descargarlo de algún sitio, como http://e-administracion.ulpgc.es/sites/default/files/AutoFirmaROOT.crt).

Tras ello, cerramos Firefox y arrancamos la aplicación Java AutoFirma, desde la que elegimos "Herramientas > Restaurar instalación". Con ello, conseguiremos que la aplicación web reconozca nuestros certificados digitales y que se puedan firmar documentos con ellos desde ese nuevo Firefox (por ejemplo en https://valide.redsara.es/valide/firmar/ejecutar.html.

NOTA: Este nuevo Firefox se actualizará si accedemos a su menú "Help > About Firefox), pero ello no da al traste con la configuración de AutoFirma.

NOTA 2: El perfil de usuario del nuevo Firefox que se crea al arrancarlo por primera vez se guarda en el mismo directorio que los perfiles de usuario que tenga el Firefox procedente de snap, es decir, en ~/.mozilla/firefox/). En mi caso, el perfil del nuevo Firefox se crea en un subdirectorio ajqd7gd9.SnapFree y el que tenía del antiguo Firefox era xqkyr2zn.default-release; quizás el hecho de que el perfil del nuevo Firefox empiece por "a" hace que AutoFirma lo reconozca primero. Por si en vuestro sistema el perfil del nuevo Firefox tiene un nombre que va ordenado alfabéticamente por detrás del perfil del Firefox antiguo, instalad los certificados digitales también en el antiguo Firefox.

Suerte!!!

**Comment by ibarbech** [comment]
He arreglado estos errores instalando la ultima version de java 

```bash
sudo apt install default-jdk default-jre
```

**Comment by Vichman67** [comment]
Ibarbech, gracias por tu aporte y me alegro que en tu sistema funcione, pero en el mío, donde no tenía instalados los default-* que mencionas, los he instalado y sigo igual: desde Firefox instalado mediante snap (a día de hoy, versión 110.0.1) no puedo firmar documentos.

Los paquetes default-jdk y default-jre me da la impresión de que son simplemente una forma diferente de llamar al Java que tengas ya instalado en tu sistema. En sus descripciones se puede leer "_This dependency package points to the Java runtime, or Java compatible development kit recommended for this architecture_".

Así que a lo mejor todo dependa en última instancia del Java que tengas instalado.

¿Puedes decirnos cuál es tu versión? Para saberlo, puedes ejecutar cualquiera de estos dos comandos (te indico para ellos lo que tengo yo, OpenJDK 11):

```
readlink -f "$(which java)"
    /usr/lib/jvm/java-11-openjdk-amd64/bin/java

java -version
    openjdk version "11.0.18" 2023-01-17
    OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
    OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

```
Saludos.

**Comment by ibarbech** [comment]
Si claro aquí tienes la salida de ambos comandos.

```bash
readlink -f "$(which java)"
    /usr/lib/jvm/java-11-openjdk-amd64/bin/java

java -version
    openjdk version "11.0.18" 2023-01-17
    OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
    OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
 ```
 Por lo que puedes ver obtengo la misma salida
 
 Saludos

**Comment by albfernandez** [comment]
> Ibarbech, gracias por tu aporte y me alegro que en tu sistema funcione, pero en el mío, donde no tenía instalados los default-* que mencionas, los he instalado y sigo igual: desde Firefox instalado mediante snap (a día de hoy, versión 110.0.1) no puedo firmar documentos.
> 
> Los paquetes default-jdk y default-jre me da la impresión de que son simplemente una forma diferente de llamar al Java que tengas ya instalado en tu sistema. En sus descripciones se puede leer "_This dependency package points to the Java runtime, or Java compatible development kit recommended for this architecture_".
> 
> Así que a lo mejor todo dependa en última instancia del Java que tengas instalado.
> 
> ¿Puedes decirnos cuál es tu versión? Para saberlo, puedes ejecutar cualquiera de estos dos comandos (te indico para ellos lo que tengo yo, OpenJDK 11):
> 
> ```
> readlink -f "$(which java)"
>     /usr/lib/jvm/java-11-openjdk-amd64/bin/java
> 
> java -version
>     openjdk version "11.0.18" 2023-01-17
>     OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
>     OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
> ```
> 
> Saludos.

Si usas Firefox instalado mediante snap, la version actual de Autofirma (1.7.1) no va a encontrar el directorio de tu perfil de Firefox.

Una solución que proponen en otros hilos, es hacer un enlace del directorio por defecto, donde va a buscarlo autofirma, al directorio del snap. Algo como esto (ojo no lo he probado, puede necesitar ajustes)

```bash
cd $HOME
mkdir .mozilla
ln -s ~/snap/firefox/common/.mozilla/firefox .mozilla/firefox
```

**Comment by Guillermogsjc** [comment]
buenas,

rogaría que la aplicación se desarrollara de tal modo que Autofirma en firma online en exploradores funcionara para distribuciones tan estándar como lo es Debian.

Que este issue lleve abierto **más de 2 años y medio a fecha de hoy** solo refleja la dejadez al respecto en tratar la característica de firma (obligada en muchas gestiones), para sistemas Linux.

Vamos, que tengo **una partición windows exclusivamente instalada para poder usar Autofirma**, cuando absolutamente **todas las demás gestiones**, las hago  a través de Linux sin problema.

No sé si es porque la contrata del ministerio no es capaz o porque el ministerio no quiere pagar por la característica de firma en explorador **bien desarrollada para todos los SO**... realmente es algo indistinto, es impermisible y bochornoso el estado de esta issue.

**Comment by gopala410** [comment]
En realidad es ilegal que te obliguen a usar windows en españa y en toda europa, esto se puede denunciar
Puedes prejudicializar tu denuncia para que la atiendan en tribunales europeos porque como comprendereis en españa no tendreis un juicio justo que atienda a esto, el gobierno se dara la razon asi mismo. Por que ocurre esto? y 
Como hacerlo ?  Pues segun esta web, aqui estaria la solucion:

https://porunajusticiaindependiente.com/

Esta incluso explicada como la cadena de mando hace que la justicia sea totalmente dependiente del poder politico puede sancionar a jueces que emitan justicia en vez de ideologia (pej denuncias falsas de violencia de genero que nunca se hace justicia y siempre se acaba abusando de los menores que son los primeros perjudicados) 
Y obviamente cualquier otro proceso o denuncia en que el estado sea juez y parte, jamas ganareis ... 

Lo dicho  podeis hacer una denuncia pre-judicializada en los tribunales de la UE y de una vez por todas conseguir que no os obliguen a comprar windows el opensource debe ser admitido por ley por todas las administraciones publicas

**Comment by backpackerhh** [comment]
> He arreglado estos errores instalando la última versión de java
> 
> ```shell
> sudo apt install default-jdk default-jre
> ```

Confirmo que haciendo eso me funciona en Ubuntu 22.04 desde Google Chrome 129.0.6668.100 (Official Build) (64-bit)

**Comment by algarsal** [comment]
En Ubuntu 24.04:
Autofirma me funciona bien por separado. 
El certificado está instalado correctamente en Firefox y Chrome. 
Pero no conseguía que funionara la comunicación entre los navegadores y autofirma. Lo cual es un problema para cualquier solicitud oficial y páginas webs de algunas universidades. 

Instalando jdk como propone @backpackerhh  he conseguido que funcione con Chrome. Pero en firefox sigue sin funcionar. (Snap 134.0.2 (64-bit)). 

Debería funcionar esa conexión o que no la pidieran las webs oficiales mientras no funcione.

**Comment by Vichman67** [comment]
> En Ubuntu 24.04: Autofirma me funciona bien por separado. El certificado está instalado correctamente en Firefox y Chrome. Pero no conseguía que funionara la comunicación entre los navegadores y autofirma. Lo cual es un problema para cualquier solicitud oficial y páginas webs de algunas universidades.
> 
> Instalando jdk como propone [@backpackerhh](https://github.com/backpackerhh) he conseguido que funcione con Chrome. Pero en firefox sigue sin funcionar. (Snap 134.0.2 (64-bit)).
> 
> Debería funcionar esa conexión o que no la pidieran las webs oficiales mientras no funcione.

Por si te sirve de algo, en mi entorno sí funciona:

- Ubuntu 24.04
- Firefox 134.0.1 instalado desde snap
- Autofirma 1.8.3
- OpenJDK 21.0.5 (21.0.5+11-1ubuntu1~24.04) instalado desde el repositorio estándar de Ubuntu)

Aunque Autofirma se queja al arrancar de que estóy usando un Java no soportado, funciona correctamente.

¿Tienes AutoFirma actualizado?
¿Has probado con la opción "Herramientas > Restaurar instalación" del propio AutoFirma?

**Comment by alwayswatchintv** [comment]
asegurarte de que todas las dependencias necesarias estén instaladas.
Puedes hacerlo con la terminal

**Comment by algarsal** [comment]
> > En Ubuntu 24.04: Autofirma me funciona bien por separado. El certificado está instalado correctamente en Firefox y Chrome. Pero no conseguía que funionara la comunicación entre los navegadores y autofirma. Lo cual es un problema para cualquier solicitud oficial y páginas webs de algunas universidades.
> > Instalando jdk como propone [@backpackerhh](https://github.com/backpackerhh) he conseguido que funcione con Chrome. Pero en firefox sigue sin funcionar. (Snap 134.0.2 (64-bit)).
> > Debería funcionar esa conexión o que no la pidieran las webs oficiales mientras no funcione.
> 
> Por si te sirve de algo, en mi entorno sí funciona:
> 
>     * Ubuntu 24.04
> 
>     * Firefox 134.0.1 instalado desde snap
> 
>     * Autofirma 1.8.3
> 
>     * OpenJDK 21.0.5 (21.0.5+11-1ubuntu1~24.04) instalado desde el repositorio estándar de Ubuntu)
> 
> 
> Aunque Autofirma se queja al arrancar de que estóy usando un Java no soportado, funciona correctamente.
> 
> ¿Tienes AutoFirma actualizado? ¿Has probado con la opción "Herramientas > Restaurar instalación" del propio AutoFirma?

A mi también se me queja del java no soportado, aunque luego funciona. Y sí, tengo Autofirma actualizado y le dí a Restaurar instalación.

**Comment by algarsal** [comment]
> asegurarte de que todas las dependencias necesarias estén instaladas.
> Puedes hacerlo con la terminal
> […](#)

¿Hay alguna dependencia que estemos pasando por alto? En principio con java debería ser suficiente. 
¿qué dependencia propones que instale?

**Comment by naknatxo** [comment]
Buenas a mi me ha funcionado abriendo el chrome desde la terminal con este comando:

`google-chrome --disable-features=BlockInsecurePrivateNetworkRequests`

OpenJdk 11

El autofirma lo habñia bajado a la 1.8.3  pero supongo que con el 1.9 habrñia funcionado también lo de abrir así el chrome

**Comment by ixti** [comment]
~@quilosaq tengo la misma problema con tu ebuild tambien.~

UPDATE: too early to say, as I have completely missed postinst instructions.

**Comment by dgarcia18** [comment]
Os comento mi caso:
- Ubuntu 24.04
- Firefox corriendo como snap
- Autofirma 1.9 instalado via archivo DEB


Al intentar arranca autofirma:


```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.getSystemNSSLibDir(MozillaKeyStoreUtilities.java:252)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:706)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:122)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:59)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:77)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:511)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:542)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:133)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:1018)
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local4>" is null
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.searchLastFirefoxVersion(MozillaKeyStoreUtilitiesUnix.java:157)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.getNssPaths(MozillaKeyStoreUtilitiesUnix.java:87)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.<clinit>(MozillaKeyStoreUtilitiesUnix.java:32)
	... 9 more 
```

Tras muchos quebraderos de cabeza, el problema estaba en que el directorio /opt solo tiene permisos de ejecucion (--x) para "otros". Esto viene así por defecto como medida de hardening en esta versión de Ubuntu. Autofirma intenta listar su contenido para buscar Firefox, llama listFiles() en /opt y recibe null, lo que hace saltar la excepción de más arriba. 

Resuelto con:
`sudo chmod o+r /opt`


Disclamer: este cambio hace que cualquier usuario pueda leer /opt y ver qué software hay instalado en el equipo. Si es un PC personal puede valer, pero ojo con servidores multiusuario.

**Comment by quilosaq** [comment]
@dgarcia18 

El problema que comentas no es nuevo en este repositorio y se puede resolver de dos maneras:

- Modificando los permisos de sistema archivos (directorio /opt)
- Parcheando el código fuente de autofirma

La modificación de los permisos en /opt es lo que cualquier usuario normal puede hacer para resolverlo aunque solo se dará en distribuciones linux "exóticas" ya que los permisos "normales" para ese directorio es 755 y en esa situación la excepción no se produce. En #469 hay un caso reciente similar al tuyo.

La solución definitiva sería corregir el código para que no cayera en una excepción no gestionada. Con esta idea hay un par de Pull requests (#313 y #367) del año 2023 que no han sido aceptadas ni rechazadas. Una lástima porque realmente funcionan.
