### ISSUE TITLE
Firmar xml "Xades enveloped" desde linea de comandos

### ISSUE THREAD

**Issue by dvarela1974** [ctt-gob-es/clienteafirma#205]
Hola.
A ver si alguien sabe la respuesta, he mirado y remirado la configuración, buscado por internet, pero no encuentro nada.
Tengo que firmar documentos xml con el formato "Xades Enveloped" con afirma desde linea de comandos, pero no se de qué manera decirselo a la aplicación. Entiendo que en el parametro -format hay que marcar "xades", pero me lo firma por defecto como "enveloping".
¿tengo que poner algo en -config?, en ese caso, ¿qué es lo que tengo que poner?.

Saludos

**Comment by joseluisartensio** [comment]
Para sistemas Windows

AutoFirmaCommandLine.exe sign -i file.xml -o file.xml_signed.xsig -store pkcs12:certificado.p12 -password xxxxxxx -filter certificado.p12 -format xades -xml -config "format=XAdES Enveloped"

Para sistemas linux
 /usr/bin/AutoFirma sign

Pero en linux no funciona el parámetro format=XAdES Enveloped

**Comment by jgrateron** [comment]
Es un problema en el script de AutoFirma

Ejecuta directamente usando java y funciona correctamente

java -jar /usr/lib/AutoFirma/AutoFirma.jar sign -i file.xml -o file_signed.xml -format xades -store pkcs12:micertificado.pfx -alias mialias -password xxxx -config "format=XAdES Enveloped"

**Comment by akitamostodos** [comment]
Hola, yo tngo un problema

ya ponga :
java -jar /usr/lib/AutoFirma/AutoFirma.jar sign -i ejemplo.xml -o 1.xml_signed.xsig -format xades -store pkcs12:EIDAS_CERTIFICADO_PRUEBAS___99999999R.p12 -password 1234 -filter subject.contains:99999999R -config "format=XAdES Enveloped";

o 

AutoFirma sign -i ejemplo.xml -o 1.xml_signed.xsig -store pkcs12:EIDAS_CERTIFICADO_PRUEBAS___99999999R.p12 -password 1234 -filter subject.contains:99999999R -format facturae -xml;


me lo firma y aparentemente voy a la web oficial a verificar firma y dice que esta correcto pero me sale el siguiente error a ver si alguien me ayuda...

Muchas gracias.

feb 28, 2022 5:15:39 PM es.gob.afirma.signers.xades.XAdESUtil <clinit>
GRAVE: No se ha podido establecer la propiedad de seguridad en la factoria XML
java.lang.IllegalArgumentException: La propiedad "http://javax.xml.XMLConstants/property/accessExternalStylesheet" no se ha reconocido.
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl.setAttribute(DocumentBuilderFactoryImpl.java:115)
        at es.gob.afirma.signers.xades.XAdESUtil.<clinit>(XAdESUtil.java:97)
        at es.gob.afirma.signers.xades.XAdESSigner.sign(XAdESSigner.java:429)
        at es.gob.afirma.signers.xades.AOXAdESSigner.sign(AOXAdESSigner.java:405)
        at es.gob.afirma.signers.xades.AOFacturaESigner.sign(AOFacturaESigner.java:128)
        at es.gob.afirma.standalone.CommandLineLauncher.sign(CommandLineLauncher.java:797)
        at es.gob.afirma.standalone.CommandLineLauncher.signByCommandLine(CommandLineLauncher.java:624)
        at es.gob.afirma.standalone.CommandLineLauncher.processCommandLine(CommandLineLauncher.java:152)
        at es.gob.afirma.standalone.CommandLineLauncher.main(CommandLineLauncher.java:1006)
        at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:573)

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
<afirma><result>true</result><response><msg>La operacion ha terminado correctamente </msg></response></afirma>

**Comment by yeyoext** [comment]
hola @akitamostodos , tengo el mismo problema, ¿Cómo resolviste?
