### ISSUE TITLE
Error al ejecutar AutoFirma en Ubuntu

### ISSUE THREAD

**Issue by jose-luis-gonzalo** [ctt-gob-es/clienteafirma#224]
Hola.

Necesito llamar desde una aplicación JavaWebStart a la aplicación de línea de comandos de AutoFirma desde Windows, Linux y Mac.
Desde Windows llamo a AutoFirmaCommandLine.exe sin problemas, pero desde Linux no lo consigo hacer.

He instalado AutoFirma 1.6.5 en Ubuntu 21.10 usando OpenJDK Runtime Environment (build 1.8.0_302-8u302-b08-0ubuntu2-b08)

He instalado y desinstalado AutoAfirma y Firefox varias veces y en distinto orden y me da este error al ejecutar AutorFirma:

Nov 11, 2021 5:20:39 PM es.gob.afirma.standalone.ProxyUtil clearJavaProxy
INFO: No se usara Proxy para las conexiones de red
Nov 11, 2021 5:20:39 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: No se buscaran nuevas versiones de la aplicacion
Nov 11, 2021 5:20:39 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFO: AutoFirma 1.6.5
Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 5.13.0-21-generic
Version de Java: 1.8.0_302
Arquitectura del JRE: 64
Java Vendor: Private Build
Localizacion por defecto: en_US
Tamano actual en memoria: 150MB
Tamano maximo de memoria: 1760MB
Memoria actualmente libre: 84MB
Nov 11, 2021 5:20:39 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Apertura como herramienta de escritorio
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Nov 11, 2021 5:20:39 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Se intenta una precarga temprana de NSS
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFO: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib/thunderbird/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='sql:/USERHOME/.mozilla/firefox/y6ol9dg1.default' certPrefix='' keyPrefix='' flags='readOnly'"
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
INFO: NSS necesita una precarga o tratamiento de sus dependencias: java.lang.reflect.InvocationTargetException
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
WARNING: Ha fallado el segundo intento de carga de NSS: java.lang.reflect.InvocationTargetException
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.mozilla.NssKeyStoreManager getNssProvider
SEVERE: Error obteniendo el proveedor NSS: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNssJava8(MozillaKeyStoreUtilities.java:680)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:727)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:122)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:59)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:72)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:511)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:542)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:133)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:646)
Caused by: java.security.ProviderException: Initialization failed
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:387)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:107)
	... 13 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: 0xCE534351
	at sun.security.pkcs11.wrapper.PKCS11.C_Initialize(Native Method)
	at sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_Initialize(PKCS11.java:1627)
	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:163)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:341)
	... 14 more

Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado un DNIe: java.security.ProviderException: No se ha podido inicializar el proveedor de DNIe: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: Tarjeta FNMT-RCM CERES 4.30 o superior
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado una tarjeta CERES 4.30 o superior: java.security.ProviderException: No se ha podido inicializar el proveedor de Ceres 4.30 y superior: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: Tarjeta FNMT-RCM CERES
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado una tarjeta CERES: java.security.ProviderException: No se ha podido conectar con la tarjeta CERES: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFO: Se incluiran los modulos nativos de DNIe/CERES si se encuentran configurados
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
SEVERE: No se han podido obtener los modulos externos de Mozilla desde 'pkcs11.txt': java.io.FileNotFoundException: /home/jose/.mozilla/firefox/y6ol9dg1.default/pkcs11.txt (Permission denied)
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
SEVERE: No se han podido obtener los modulos externos de Mozilla desde 'secmod.db': es.gob.afirma.core.AOException: El directorio del perfil de Mozilla proporcionado no contiene una base de datos de modulos (secmod.db)
Nov 11, 2021 5:20:39 PM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
INFO: No se han encontrado modulos PKCS#11 externos instalados en Firefox
Nov 11, 2021 5:20:39 PM es.gob.afirma.standalone.SimpleAfirma setKeyStoreManager
INFO: Establecido KeyStoreManager: Gestor de almacenes de claves Mozilla / Firefox (unificado) con nombre Mozilla / Firefox (unificado)
Nov 11, 2021 5:20:39 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Cargando plugins
Nov 11, 2021 5:20:39 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Iniciando entorno grafico
Nov 11, 2021 5:20:40 PM es.gob.afirma.standalone.SimpleAfirma loadDefaultKeyStore
INFO: Se omite la carga concurrente de almacen por haberse hecho una precarga previa

¿Alguna pista de por qué da este error?

Muchas gracias

**Comment by profesors** [comment]
Tampoco puedo y esto es lo que puedo ver. Ojalá encontrásemos una solución:

```
jun 12, 2022 1:02:11 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Invocacion por protocolo con URL:
afirma://websocket?v=3&idsession=TafaF28L7EkrjNERZkkz
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
jun 12, 2022 1:02:11 PM es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher launch
INFORMACIÓN: Se inicia el modo de comunicacion por websockets: afirma://websocket?v=3&idsession=TafaF28L7EkrjNERZkkz
jun 12, 2022 1:02:11 PM es.gob.afirma.standalone.protocol.SecureSocketUtils getSecureSSLContext
INFORMACIÓN: Se utilizara el siguiente almacen para establecer el socket SSL: /usr/lib/AutoFirma/autofirma.pfx
jun 12, 2022 1:03:11 PM es.gob.afirma.standalone.protocol.AfirmaWebSocketServer lambda$startService$0
ADVERTENCIA: Se ha caducado la conexion. Se deja de escuchar en el puerto...

```

**Comment by profesors** [comment]
Finalmente pude encontrar una solución:

**He instalado Oracle 8 sobre Ubuntu 20 y ha funcionado bien** siguiendo esta guía https://www.fosstechnix.com/install-oracle-java-8-on-ubuntu-20-04/

Ojalá que pueda servir de ayuda a otras personas
