### ISSUE TITLE
Nuevos problemas con fedora 33 y autofirma

### ISSUE THREAD

**Issue by gopala410** [ctt-gob-es/clienteafirma#230]
Despues de que funciono una vez, vuelve a fallar
Vuelvo a tener problemas con autofirma en fedora 33.
me funciono durante unos meses pero ahora al ejecutarlo, no arranca dando el siguiente error:

autofirma
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
at java.desktop/java.awt.Color.(Color.java:275)
at es.gob.afirma.standalone.LookAndFeelManager.(LookAndFeelManager.java:60)
at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549)

Que puedo hacer ? hay alguna forma de que esto funcione para siempre ?

**Comment by LucasFA** [comment]
#302
