### ISSUE TITLE
Excepción en autofirma. ¿Soporta firefox ESR en Linux?

### ISSUE THREAD

**Issue by jsegarraf** [ctt-gob-es/clienteafirma#252]
Buenos días,
hace poco actualicé Autofirma 1.6.5 a la versión 1.7.1 de Linux. La aplicación ha dejado de funcionar completamente. Justo antes de los mensajes de excepción hay un warning diciendo que la versión de firefox detectada no está soportada. La versión de firefox en mi sistema es actualmente "Mozilla Firefox 91.5.0esr" (es la que viene por defecto).

Al lanzar autofirma, aparece el siguiente log:
Mar 11, 2022 11:26:16 AM es.gob.afirma.standalone.ProxyUtil setProxySettings
INFO: No se usara proxy para las conexiones HTTP
Mar 11, 2022 11:26:16 AM es.gob.afirma.standalone.ProxyUtil setProxySettings
INFO: No se usara proxy para las conexiones HTTPS
Mar 11, 2022 11:26:16 AM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFO: AutoFirma 1.7.1
Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 5.16.0-1-amd64
Version de Java: 11.0.14
Arquitectura del JRE: 64
Java Vendor: Debian
Localizacion por defecto: en_US
Tamano actual en memoria: 252MB
Tamano maximo de memoria: 3980MB
Memoria actualmente libre: 236MB
Mar 11, 2022 11:26:16 AM es.gob.afirma.standalone.SimpleAfirma main
INFO: Apertura como herramienta de escritorio
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mar 11, 2022 11:26:16 AM es.gob.afirma.standalone.SimpleAfirma main
INFO: Se intenta una precarga temprana de NSS
Mar 11, 2022 11:26:16 AM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
INFO: Inicializamos el almacen de tipo: NSS
Mar 11, 2022 11:26:16 AM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix searchLastFirefoxVersion
WARNING: Se encontro un numero de version de Firefox no soportado: esr
Exception in thread "main" java.lang.ExceptionInInitializerError
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.getSystemNSSLibDir(MozillaKeyStoreUtilities.java:251)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:694)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:122)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:59)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:75)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:511)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:542)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:133)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:708)
Caused by: java.lang.NullPointerException
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.searchLastFirefoxVersion(MozillaKeyStoreUtilitiesUnix.java:145)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.getNssPaths(MozillaKeyStoreUtilitiesUnix.java:78)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.<clinit>(MozillaKeyStoreUtilitiesUnix.java:26)
	... 9 more

**Comment by juanjosepablos** [comment]
Tengo Firefox 91.8.0esr (64-bit), autofirma 1.7.1  y me funciona.
