### ISSUE TITLE
AutoFirma lanza excepcion al arrancar en Ubuntu 16.04 (32 bits)

### ISSUE THREAD

**Issue by xetum** [ctt-gob-es/clienteafirma#26]
Esto es lo que se escribe:

`francesc@francesc:/tmp$ AutoFirma 
d’abr. 05, 2018 6:24:26 PM es.gob.afirma.standalone.LookAndFeelManager applyLookAndFeel
INFO: Establecido 'Look&Feel' GTK look and feel
d’abr. 05, 2018 6:24:26 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Se intenta una precarga temprana de NSS
d’abr. 05, 2018 6:24:26 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFO: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib/firefox/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='USERHOME/.mozilla/firefox/lnb18ajg.default' certPrefix='' keyPrefix='' flags='readOnly'"
d’abr. 05, 2018 6:24:26 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
INFO: NSS necesita una precarga o tratamiento de sus dependencias: java.lang.reflect.InvocationTargetException
d’abr. 05, 2018 6:24:26 PM es.gob.afirma.keystores.mozilla.NssKeyStoreManager getNssProvider
SEVERE: Error obteniendo el proveedor NSS: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNssJava8(MozillaKeyStoreUtilities.java:558)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:603)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:112)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:59)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:67)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:446)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:480)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:119)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:541)
Caused by: java.security.ProviderException: Initialization failed
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:376)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:107)
	... 13 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DEVICE_ERROR
	at sun.security.pkcs11.wrapper.PKCS11.C_Initialize(Native Method)
	at sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_Initialize(PKCS11.java:1545)
	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:157)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:330)
	... 14 more

d’abr. 05, 2018 6:24:26 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules`

**Comment by s-nt-s** [comment]
Quiza esto te sirva: https://github.com/ctt-gob-es/clienteafirma/issues/29#issuecomment-380535753
