### ISSUE TITLE
Errores java de AutoFirma en Linux Mint 18.3 64bits

### ISSUE THREAD

**Issue by s-nt-s** [ctt-gob-es/clienteafirma#29]
Errores java en el arranque del `AutoFirma` en `Linux Mint 18.3 64bits`, con el resultado de que la aplicación no llega a abrirse y por lo tanto no se puede usar.

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia
$ uname -a
Linux ya 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 8.0.5.10 - pxa6480sr5fp10-20180214_01(SR5 FP10))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180208_378436 (JIT enabled, AOT enabled)
OpenJ9   - 39bb844
OMR      - c04ccb2
IBM      - 2321a81)
JCL - 20180209_01 based on Oracle jdk8u161-b12
$ AutoFirma 
abr 11, 2018 6:36:04 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFORMACIÓN: Las conexiones para protocolo 'http' son por defecto de tipo: DIRECT
abr 11, 2018 6:36:04 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFORMACIÓN: Las conexiones para protocolo 'https' son por defecto de tipo: DIRECT
abr 11, 2018 6:36:04 PM es.gob.afirma.standalone.ProxyUtil setProxySettings
INFORMACIÓN: No se usara Proxy para las conexiones de red
abr 11, 2018 6:36:04 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: No se buscaran nuevas versiones de la aplicacion
abr 11, 2018 6:36:04 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFORMACIÓN: Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 4.8.0-53-generic
Version de Java: 1.8.0_161
Arquitectura del JRE: 64
Java Vendor: IBM Corporation
Localizacion por defecto: es_ES
Tamano actual en memoria: 27MB
Tamano maximo de memoria: 512MB
Memoria actualmente libre: 1MB
abr 11, 2018 6:36:04 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Apertura como herramienta de escritorio
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org.slf4j.impl.StaticLoggerBinder
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:121)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:111)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:268)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:241)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:254)
	at com.dmurph.tracking.JGoogleAnalyticsTracker.<clinit>(JGoogleAnalyticsTracker.java:94)
	at es.gob.afirma.standalone.SimpleAfirma.lambda$main$0(SimpleAfirma.java:502)
	at es.gob.afirma.standalone.SimpleAfirma$$Lambda$12.000000002CD14660.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:609)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:332)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	... 9 more
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: org.slf4j.impl.StaticLoggerBinder
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:121)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:111)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:268)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:241)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:254)
	at com.dmurph.tracking.JGoogleAnalyticsTracker.<clinit>(JGoogleAnalyticsTracker.java:94)
	at es.gob.afirma.standalone.SimpleAfirma.lambda$main$0(SimpleAfirma.java:502)
	at es.gob.afirma.standalone.SimpleAfirma$$Lambda$12.000000002CD14660.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:609)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:332)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	... 9 more
abr 11, 2018 6:36:06 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Se intenta una precarga temprana de NSS
abr 11, 2018 6:36:06 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFORMACIÓN: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib/thunderbird/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='sql:/USERHOME/.mozilla/firefox/mwad0hks.default' certPrefix='' keyPrefix='' flags='readOnly'"
abr 11, 2018 6:36:06 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
INFORMACIÓN: NSS necesita una precarga o tratamiento de sus dependencias: java.lang.ClassNotFoundException: sun.security.pkcs11.SunPKCS11
abr 11, 2018 6:36:06 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
AVISO: Ha fallado el segundo intento de carga de NSS: java.lang.ClassNotFoundException: sun.security.pkcs11.SunPKCS11
abr 11, 2018 6:36:06 PM es.gob.afirma.keystores.mozilla.NssKeyStoreManager getNssProvider
GRAVE: Error obteniendo el proveedor NSS: java.lang.ClassNotFoundException: sun.security.pkcs11.SunPKCS11
java.lang.ClassNotFoundException: sun.security.pkcs11.SunPKCS11
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:297)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNssJava8(MozillaKeyStoreUtilities.java:669)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:718)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:111)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:58)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:68)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:488)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:519)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:116)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:571)

abr 11, 2018 6:36:06 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFORMACIÓN: Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF
Exception in thread "main" java.lang.NoClassDefFoundError: javax.smartcardio.CardException
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:297)
	at es.gob.jmulticard.jse.provider.DnieProvider.<init>(DnieProvider.java:97)
	at es.gob.jmulticard.jse.provider.DnieProvider.<init>(DnieProvider.java:87)
	at es.gob.afirma.keystores.AOKeyStoreManagerHelperFullJava.initDnieJava(AOKeyStoreManagerHelperFullJava.java:93)
	at es.gob.afirma.keystores.AOKeyStoreManager.init(AOKeyStoreManager.java:213)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getDnieJavaKeyStoreManager(AOKeyStoreManagerFactory.java:300)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:132)
	at es.gob.afirma.keystores.KeyStoreUtilities.getDnieKeyStoreManager(KeyStoreUtilities.java:389)
	at es.gob.afirma.keystores.KeyStoreUtilities.addPreferredKeyStoreManagers(KeyStoreUtilities.java:322)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:83)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:488)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:519)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:116)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:571)
Caused by: java.lang.ClassNotFoundException: javax.smartcardio.CardException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:609)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:332)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	... 15 more```

**Comment by s-nt-s** [comment]
Si se instala Oracle Java tal como dice aquí http://tipsonubuntu.com/2016/07/31/install-oracle-java-8-9-ubuntu-16-04-linux-mint-18/ funciona:

```console
$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
$ AutoFirma 
abr 11, 2018 7:36:34 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFORMACIÓN: Las conexiones para protocolo 'http' son por defecto de tipo: DIRECT
abr 11, 2018 7:36:34 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFORMACIÓN: Las conexiones para protocolo 'https' son por defecto de tipo: DIRECT
abr 11, 2018 7:36:34 PM es.gob.afirma.standalone.ProxyUtil setProxySettings
INFORMACIÓN: No se usara Proxy para las conexiones de red
abr 11, 2018 7:36:34 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: No se buscaran nuevas versiones de la aplicacion
abr 11, 2018 7:36:34 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFORMACIÓN: Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 4.8.0-53-generic
Version de Java: 1.8.0_161
Arquitectura del JRE: 64
Java Vendor: Oracle Corporation
Localizacion por defecto: es_ES
Tamano actual en memoria: 75MB
Tamano maximo de memoria: 857MB
Memoria actualmente libre: 51MB
abr 11, 2018 7:36:34 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Apertura como herramienta de escritorio
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
abr 11, 2018 7:36:35 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Se intenta una precarga temprana de NSS
abr 11, 2018 7:36:35 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFORMACIÓN: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib/thunderbird/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='sql:/USERHOME/.mozilla/firefox/mwad0hks.default' certPrefix='' keyPrefix='' flags='readOnly'"
abr 11, 2018 7:36:35 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
INFORMACIÓN: NSS necesita una precarga o tratamiento de sus dependencias: java.lang.reflect.InvocationTargetException
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFORMACIÓN: Proveedor PKCS#11 para NSS anadido: SunPKCS11-NSSCrypto-AFirma
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFORMACIÓN: Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFORMACIÓN: No se ha encontrado un DNIe: java.security.ProviderException: No se ha podido inicializar el proveedor de DNIe: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFORMACIÓN: Se incluiran los modulos nativos de DNIe/CERES si se encuentran configurados
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFORMACIÓN: Obtenidos los modulos externos de Mozilla desde 'pkcs11.txt'
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
INFORMACIÓN: Encontrados los siguientes modulos PKCS#11 externos instalados en Mozilla / Firefox: '/usr/lib/libpkcs11-dnie.so' 
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFORMACIÓN: Inicializamos el almacen de tipo: PKCS#11
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.KeyStoreUtilities createPKCS11ConfigFile
INFORMACIÓN: Creada configuracion PKCS#11:
library=/usr/lib/libpkcs11-dnie.so
name=libpkcs11-dnie_so
showInfo=false

abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFORMACIÓN: Inicializamos el almacen de tipo: PKCS#11
abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.KeyStoreUtilities createPKCS11ConfigFile
INFORMACIÓN: Creada configuracion PKCS#11:
library=/usr/lib/libpkcs11-dnie.so
name=libpkcs11-dnie_so
showInfo=false

abr 11, 2018 7:36:36 PM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
ADVERTENCIA: No se ha podido inicializar el PKCS#11 'DNIe módulo PKCS#11' tras haberlo intentado dos veces: es.gob.afirma.keystores.AOKeyStoreManagerException: No se ha podido instanciar el proveedor SunPKCS11 para la la biblioteca /usr/lib/libpkcs11-dnie.so: java.lang.reflect.InvocationTargetException, es.gob.afirma.keystores.AOKeyStoreManagerException: No se ha podido instanciar el proveedor SunPKCS11 para la la biblioteca /usr/lib/libpkcs11-dnie.so: java.lang.reflect.InvocationTargetException
abr 11, 2018 7:36:36 PM es.gob.afirma.standalone.SimpleAfirma setKeyStoreManager
INFORMACIÓN: Establecido KeyStoreManager: Gestor de almacenes de claves Mozilla / Firefox (unificado) con nombre Mozilla / Firefox (unificado)
abr 11, 2018 7:36:37 PM es.gob.afirma.standalone.SimpleAfirma loadDefaultKeyStore
INFORMACIÓN: Se omite la carga concurrente de almacen por haberse hecho una precarga previa
```

y se abre la apliación.

Aún así considero que la aplicación debería funcionar con openjdk.

**Comment by raultm** [comment]
Buenas,

Estaba teniendo problemas con autofirma (Xubuntu 18.04 usando Mozilla como almacen de claves), me arrancaba y me dejaba hacer todo pero me decía que no encontraba nada en el almacen de claves. En otro ordenador que he probado sí. He mirado y en XUbuntu 18 tenia open jdk, mientras que en el que si funcionaba tenia java 1.8. He cambiado OpenJDK por Java1.8 y ya me funciona.

¿Se va a poder usar autofirma con openjdk?

**Comment by LuisLlana** [comment]
Parece que AutoFirma es incompatible con las versiones de openjdk 10 y 11. Funciona bien con el openjdk-8

**Comment by calvaris** [comment]
A mí no me encontraba los certificados y haciendo 1.8 la versión por defecto en mis debian alternatives me ha funcionado.

**Comment by amunozf** [comment]
> A mí no me encontraba los certificados y haciendo 1.8 la versión por defecto en mis debian alternatives me ha funcionado.

Confirmo que funciona poniendo como versión predeterminada de java la openjdk 8 en Kde Neon 18.04 (y supongo que debería ser igual para cualquier otra basada en Debian o Ubuntu).

Hay que instalar el paquete openjdk-8-jre

`sudo apt install openjdk-8-jre`

Después hay que cambiar la versión predeterminada de java por la 8, para que autofirma use la versión 8 en vez de la 11.

`sudo update-alternatives --all`

Y hay pulsar el número que corresponda a la versión 8 (en mi caso, el 2). Debe aparecer un texto similar a este varias veces:

```
  Selección   Ruta                                                 Prioridad  Estado
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200      1101      modo automático
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200      1101      modo manual
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/unpack200   1081      modo manual

```

También he tenido que reinstalar autofirma:

```
sudo apt purge autofirma
sudo dpkg -i AutoFirma_1_6_2.deb
```

Y borrar la configuración de autofirma de cada usuario:

`rm -rf /home/usuario/.afirma`

Espero que sirva de ayuda. Gracias @calvaris por tu sugerencia.

Puede que haya que hacer hacer el proceso inverso (seleccionar la versión 11 en vez de la 8) cuando un programa no funcione con la 8 y sí con la 11.

**Comment by lorenzogrv** [comment]
Paso por aquí para comentar que la solución propuesta por @amunozf sigue siendo funcional, al menos en tanto no salga un release nuevo.

PD: `sudo update-alternatives --config java` es más directo para cambiar la versión.

**Comment by AlmuHS** [comment]
> Paso por aquí para comentar que la solución propuesta por @amunozf sigue siendo funcional, al menos en tanto no salga un release nuevo.
> 
> PD: `sudo update-alternatives --config java` es más directo para cambiar la versión.

Sí, eso ya lo he hecho. Y tengo puesto Oracle JDK 8, pero me sigue dando ese aviso al arrancar Autofirma, y me falla al arrancarlo desde el navegador

**Comment by alfem** [comment]
Yo estoy usando autofirma 1.6.5 con OpenJDK 11 en Mint Tricia sin problema alguno.

**Comment by AlmuHS** [comment]
> Yo estoy usando autofirma 1.6.5 con OpenJDK 11 en Mint Tricia sin problema alguno.

Si, lo que es la aplicación funciona sin problemas: se abre, firma... Pero, si lo abres desde consola, sale este aviso:

```
ADVERTENCIA: No se ha podido inicializar el PKCS#11 'Nuevo módulo PKCS#11' tras haberlo intentado dos veces: es.gob.afirma.keystores.AOKeyStoreManagerException: No se ha podido instanciar el proveedor SunPKCS11 para la la biblioteca '/usr/lib/libpkcs11-dnie.so': java.lang.reflect.InvocationTargetException, es.gob.afirma.keystores.AOKeyStoreManagerException: No se ha podido instanciar el proveedor SunPKCS11 para la la biblioteca '/usr/lib/libpkcs11-dnie.so': java.lang.reflect.InvocationTargetException
feb. 17, 2021 7:49:47 P. M. es.gob.afirma.standalone.SimpleAfirma setKeyStoreManager
```
Y, cuando entro a algunas páginas web que usan Autofirma para firmar documentos, justamente fallan con ese tipo de error

**Comment by alfem** [comment]
> Si, lo que es la aplicación funciona sin problemas: se abre, firma... Pero, si lo abres desde consola, sale este aviso:

A mí me salen algunas advertencias, porque no encuentra lector de tarjetas, pero esa que dices no. 

Yo probaría con java 11 y el último Autofirma. En el primer post parece que tienes la 1.6.2.

**Comment by AlmuHS** [comment]
> > Si, lo que es la aplicación funciona sin problemas: se abre, firma... Pero, si lo abres desde consola, sale este aviso:
> 
> A mí me salen algunas advertencias, porque no encuentra lector de tarjetas, pero esa que dices no.
> 
> Yo probaría con java 11 y el último Autofirma. En el primer post parece que tienes la 1.6.2.

Tengo la 1.6.5, que creo que es la última versión

**Comment by lorenzogrv** [comment]
En la oficina tuve que aplicar este fix por problemas con algún pdf concreto, lo cierto es que ahora no recuerdo cual en concreto pero en cualquier caso era formularios oficiales de sede.xuntal.gal

El mensaje al lanzarla desde terminal era similar al que comenta @AlmuHS 

La aplicación efectivamente resultaba funcional con el openjdk 11, pero el comportamiento resultaba inconsistente en algunas situaciones.

**Comment by ekoume** [comment]
I had the same problem and that it is how I solved the problem. I use Linux Ubuntu 20.04 . 

Previously I had Autofirma worked with Java8. The Installation is explained here (https://www.pcrednet.com/blog/10008-tutoriales/90-instalar-autofirma-en-ubuntu-18-04-y-linux-mint-19).

In 02.2022 , they build the new version of Autofirma and I was not able to sign some government website. 

So I uninstall both Autofirma and Java8 from my computer. An then Install the new version of Autofirma.

After trying to sign, I had the message <<SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".>>

So I installed maven with command : sudo apt install maven

Then, enter the command : mvn --version . I received the message : The JAVA_HOME environment variable is not defined correctly. This environment variable is needed to run this program . NB: JAVA_HOME should point to a JDK not a JRE.

So, I modify the bashrc file (command is sudo nano ~/.bashrc), with adding those lines:
                   export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
                   export PATH="$JAVA_HOME/bin:$PATH" 
Then enter : source ~/.profile

Now by entering the command : mvn --version , I do not obtained error anymore. But it is not finish. SLF4J error is still there.

Now I installed libslf4j-java with the command sudo apt-get install -y libslf4j-java  .  I report the version of libslf4j-java installed (my own is the version 1.7.25-3).

Now, I downloaded, slf4j-nop.jar slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar as explained in the webpage (https://www.slf4j.org/codes.html#StaticLoggerBinder). You can access to those files by this webpage (https://repo1.maven.org/maven2/org/slf4j/) , and then download the version corresponding to the version of libslf4j-java .

Now, In the folder /usr/share/maven-repo/org/slf4j , for examle rename the file slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar byslf4j-simple/1.7.25/slf4j-simple-1.7.25old.jar  . Now copy the file  slf4j-simple-1.7.25.jar you downloaded in the folder /usr/share/maven-repo/org/slf4j/slf4j-simple/1.7.25/  .   Do the same process for nop, log4j12 and jdk14  .

And that's all. I can signe document. Sorry for my English
