### ISSUE TITLE
Error al firmar un PDF con Autofirma v1.8.0

### ISSUE THREAD

**Issue by antoniovazquezblanco** [ctt-gob-es/clienteafirma#334]
Adjunto log del error:

 ```
java.lang.ClassCastException: class com.aowagie.text.pdf.PdfDictionary cannot be cast to class com.aowagie.text.pdf.PRIndirectReference (com.aowagie.text.pdf.PdfDictionary and com.aowagie.text.pdf.PRIndirectReference are in unnamed module of loader 'app')
      at com.aowagie.text.pdf.AcroFields.fill(AcroFields.java:180)
      at com.aowagie.text.pdf.AcroFields.<init>(AcroFields.java:152)
      at com.aowagie.text.pdf.PdfReader.getAcroFields(PdfReader.java:3001)
      at es.gob.afirma.signers.pades.PdfUtil.getAppendMode(PdfUtil.java:216)
      at es.gob.afirma.signers.pades.PdfSessionManager.getSessionData(PdfSessionManager.java:392)
      at es.gob.afirma.signers.pades.PAdESTriPhaseSigner.preSign(PAdESTriPhaseSigner.java:177)
      at es.gob.afirma.signers.pades.AOPDFSigner.sign(AOPDFSigner.java:201)
      at es.gob.afirma.standalone.ui.SignPanelSignTask.signData(SignPanelSignTask.java:554)
      at es.gob.afirma.standalone.ui.SignPanelSignTask.doSignature(SignPanelSignTask.java:314)
      at es.gob.afirma.standalone.ui.SignPanelSignTask.doInBackground(SignPanelSignTask.java:133)
      at es.gob.afirma.standalone.ui.SignPanelSignTask.doInBackground(SignPanelSignTask.java:73)
      at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
      at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
      at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by antoniovazquezblanco** [comment]
Se trata de una operación de firma con DNI en un documento PDF. Por desgracia no puedo aportar el documento por temas de confidencialidad. Si se necesitan datos particulares del fichero puedo aportarlos. Gracias

**Comment by rodrigoSantamaria** [comment]
Me ha ocurrido el mismo error. Nunca antes me había pasado, y uso Autofirma regularmente. Desgraciadamente tampoco puedo aportar el PDF.

**Comment by fernandouribe** [comment]
@Gamuci . Nos ha ocurrido lo mismo en un cliente con un documento que tampoco puedo aportar por razones de confidencialidad. 

Por aportar más información el problema no se reproduce con la versión 1.7.2 y si con las 1.8.2 y 1.8.3. Anexo log de autofirma por si diera más información [AUTOFIRMA.afirma_error.zip](https://github.com/user-attachments/files/17128973/AUTOFIRMA.afirma_error.zip).

**Comment by edavisx** [comment]
Me ha dado el mismo error al tratar de firmar un PDF, con la versión 1.8.2 (recién actualizada, supongo que en el reciente Upgrade, bajo GNU-Linux Debian). Sin embargo, al probar en la web https://sede.carm.es/cryptoApplet/ayuda/probarautofirma.html y al efectivamente hacer un Registro en https://reg.redsara.es/, me ha devuelto respuesta positiva (ha funcionado, aparentemente).
