### ISSUE TITLE
[Question] What does this error "SCARD_W_UNRESPONSIVE_CARD" indicate?

### ISSUE THREAD

**Issue by p4535992** [ctt-gob-es/clienteafirma#352]
Project Version: 1.8.2
Jar Used : clienteafirma-1.8.2/afirma-simple/target/AutoFirma.jar
S.O: Windows 11
Windows Command used:` java -jar AutoFirma.jar`
Java version used:` java -version`
_openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)_

When I try to read my smartcard I get this error, can you clarify what it indicates ? Do I perhaps need to install any specific drivers ? Thank you

```
java.security.ProviderException: No se ha podido inicializar el proveedor de DNIe
      at es.gob.jmulticard.jse.provider.DnieProvider.<init>(DnieProvider.java:116)
      at es.gob.jmulticard.jse.provider.DnieProvider.<init>(DnieProvider.java:92)
      at es.gob.afirma.keystores.AOKeyStoreManagerHelperFullJava.initDnieJava(AOKeyStoreManagerHelperFullJava.java:94)
      at es.gob.afirma.keystores.AOKeyStoreManager.init(AOKeyStoreManager.java:242)
      at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getDnieJavaKeyStoreManager(AOKeyStoreManagerFactory.java:323)
      at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:149)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStoreManager(SimpleKeyStoreManager.java:161)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:58)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManager.getKeyStore(SimpleKeyStoreManager.java:100)
      at es.gob.afirma.standalone.SimpleKeyStoreManagerWorker.doInBackground(SimpleKeyStoreManagerWorker.java:43)
      at es.gob.afirma.standalone.SimpleKeyStoreManagerWorker.doInBackground(SimpleKeyStoreManagerWorker.java:20)
      at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: es.gob.jmulticard.apdu.connection.ApduConnectionException: No se ha podido abrir la conexion con el lector de tarjetas numero 0
      at es.gob.jmulticard.jse.smartcardio.SmartcardIoConnection.open(SmartcardIoConnection.java:260)
      at es.gob.jmulticard.card.dnie.Dnie.connect(Dnie.java:320)
      at es.gob.jmulticard.jse.provider.DnieProvider.<init>(DnieProvider.java:112)
      ... 28 more
Caused by: javax.smartcardio.CardException: connect() failed
      at java.smartcardio/sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:85)
      at es.gob.jmulticard.jse.smartcardio.SmartcardIoConnection.open(SmartcardIoConnection.java:254)
      ... 30 more
Caused by: sun.security.smartcardio.PCSCException: SCARD_W_UNRESPONSIVE_CARD
      at java.smartcardio/sun.security.smartcardio.PCSC.SCardConnect(Native Method)
      at java.smartcardio/sun.security.smartcardio.CardImpl.<init>(CardImpl.java:97)
      at java.smartcardio/sun.security.smartcardio.TerminalImpl.connect(TerminalImpl.java:79)
      ... 31 more

```

**Comment by quilosaq** [comment]
Check your device manager for a problem (missing drivers) with the smart card.

**Comment by p4535992** [comment]
OK i installed the drivers and now i get this error:

![](https://i.imgur.com/RqS0lM6.png)

sadly I don't quite understand the error.  Is still a driver problem with the smartcard ?

**Comment by quilosaq** [comment]
What kind of smartcard do you have? Who is the issuer? I suppose it is not a Spanish [dni-e](https://www.dnielectronico.es/PortalDNIe/)

**Comment by p4535992** [comment]
Yes you are right (I had come to that at this time too), it is not an dni-e card, that is why it does not work.
Thanks for the support I will close the ticket.
