### ISSUE TITLE
Autofirma 1.82 falla al lanzar en linux (Fedora 37)

### ISSUE THREAD

**Issue by Dragnell87** [ctt-gob-es/clienteafirma#355]
Cuando se intenta lanzar la aplicación falla con el siguiente error

`autofirma 
Exception in thread "main" java.lang.NoSuchMethodError: getPeer_NoClientCode
	at java.desktop/java.awt.Font.initIDs(Native Method)
	at java.desktop/java.awt.Font.<clinit>(Font.java:289)
	at java.desktop/sun.java2d.SunGraphics2D.<clinit>(SunGraphics2D.java:212)
	at java.desktop/sun.java2d.loops.GraphicsPrimitiveMgr.initIDs(Native Method)
	at java.desktop/sun.java2d.loops.GraphicsPrimitiveMgr.<clinit>(GraphicsPrimitiveMgr.java:56)
	at java.desktop/sun.java2d.loops.Blit.<clinit>(Blit.java:114)
	at java.desktop/sun.java2d.xr.XRPMBlitLoops.register(XRPMBlitLoops.java:46)
	at java.desktop/sun.java2d.xr.XRSurfaceData.initXRSurfaceData(XRSurfaceData.java:107)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:123)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)
	at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
	at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:224)
	at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599)
	at es.gob.afirma.standalone.AutoFirmaUtil.<clinit>(AutoFirmaUtil.java:42)
	at es.gob.afirma.standalone.SimpleAfirma.getPluginsDir(SimpleAfirma.java:1117)
	at es.gob.afirma.standalone.SimpleAfirma.<clinit>(SimpleAfirma.java:184)
`
Fedora 37 64Bit
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc37) (build 17.0.7+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc37) (build 17.0.7+7, mixed mode, sharing)
Xserver  Wayland.

**Comment by LucasFA** [comment]
Vaya, veo que este issue es más reciente de lo que pensaba. Lee el issue #302, si no me equivoco te falta parte de la dependencia del runtime de Java, que probablemente tengas instalada como headless (sin interfaz de usuario)

El issue es más breve, pero la documentación oficial está en [esta página del gobierno](https://administracionelectronica.gob.es/ctt/clienteafirma/descargas) o en [ctt-gob-es/clienteafirma-docs](https://github.com/ctt-gob-es/clienteafirma-docs)
