### ISSUE TITLE
SAF_45

### ISSUE THREAD

**Issue by TraumaEnSOes** [ctt-gob-es/clienteafirma#379]
Cualquier intento de uso desde el navegador muestra el error **SAF_45**

> es.gob.afirma.standalone.protocol.SocketOperationException: No se ha podido abrir ningun socket. Se aborta la comunicacion.
>       at es.gob.afirma.standalone.protocol.AfirmaWebSocketServerManager.startService(AfirmaWebSocketServerManager.java:92)
>       at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher.launch(ProtocolInvocationLauncher.java:240)
>       at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher.launch(ProtocolInvocationLauncher.java:138)
>       at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:691)
> 

Probado en

- Brave 1.62.162 Chromium: 121.0.6167.164 (Build oficial) (64 bits)
- Firefox 122.0.1 64 bits

> java --version
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

> uname -a
Linux tuxedo 6.5.0-10022-tuxedo #26 SMP PREEMPT_DYNAMIC Thu Jan 18 02:29:42 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

- libc6 2.35-0ubuntu3.6
- libnss3-tools 2:3.68.2-0ubuntu1.2

**Comment by narcisgarcia** [comment]
He reproducido el mismo error con Debian GNU/Linux 12 en una sesión «Live».

- Navegador M. Firefox 102.15.1esr
- Navegador M. Firefox 115.7.0esr
- Navegador Brave 1.67.123 (basado en Chromium 126.0.6478.126)

Tanto he probado con el Java predeterminado (openjdk-17-jre) como reemplazándolo por el antiguo (openjdk-11-jre del repositorio unstable)

Autofirma: v1.8.3

**Comment by narcisgarcia** [comment]
He probado a instalar otra versión de AutoFirma (1.8.0) y luego reinstalar la versión 1.8.3 , y ya me funciona.
No sé si hubiera bastado con reinstalar AutoFirma con la versión deseada. algo extraño eso de arreglarse con una reinstalación (_chapuza típica de Windows_)

**Comment by fguendling** [comment]
Que locura es esto. En serio. Se pide ahora que todo el país tenga doctorado en informática? Llevo HORAS con esa aplicación y todavía sin solución

**Comment by Juarrox** [comment]
> He probado a instalar otra versión de AutoFirma (1.8.0) y luego reinstalar la versión 1.8.3 , y ya me funciona. No sé si hubiera bastado con reinstalar AutoFirma con la versión deseada. algo extraño eso de arreglarse con una reinstalación (_chapuza típica de Windows_)

Chapuza o no es la única forma de solucionar estos bugs. Yo lo he conseguido arreglar desinstalando Autofirma 1.8.3 (la última disponible para Debian 12) e instalando la versión 1.8.2. Da rabia que tengamos en Linux este soporte tan pésimo.

**Comment by qupro** [comment]
Mismo error en Linux y Firefox. Con una reinstalación se solucionó.

El problema podría venir de haber instalado primero Autofirma y luego Java (sudo apt install openjdk-11-jre), 
en lugar de al revés.

**Comment by lauramcastro** [comment]
Confirmo contexto (Debian 12, Firefox), problemática (SAF_45 al firmar vía web) y solución (desinstalar Autofirma y volverlo a instalar, en mi caso 1.8.3).

Probablemente también la causa indicada por @qupro: haber instalado primero Autofirma y luego java. La aplicación de escritorio, no obstante, funcionaba sin problemas, y la autenticación con certificado en web también. Solo fallaba la firma en web.

**Comment by pctripsesp** [comment]
Mismo error al firmar en navegador
- Autofirma 1.8.3
- Ubuntu 24.04.1 LTS

**Solución reinstalar**
```
sudo apt remove --purge autofirma
sudo dpkg -i AutoFirma_1_8_3.deb
```

**Comment by oriolarcas** [comment]
Confirmo el problema en Debian 13 con Autofirma 1.8.3 y Firefox 133.

También confirmo que la solución es reinstalar Autofirma:

```
sudo apt purge autofirma
sudo apt install ./AutoFirma_1_8_3.deb
```

**Comment by fontanon** [comment]
Pienso (opinión) que el navegador no es el problema. En la consola del navegador (inspector) se puede observar como el navegador intenta abrir websocket contra AutoFirma y no puede, y el diálogo de error lo presenta AutoFirma, no el navegador. Teoría loca: coincide que me dejase de funcionar tras instalar dnie (paquete debian descargado de la web de la policía). 

Confirmo error y solución:

Autofirma 1.8.3
Ubuntu 24.04.1 LTS

```
sudo apt remove --purge autofirma
sudo dpkg -i AutoFirma_1_8_3.deb
```

**Comment by alfonsogijon** [comment]
> Pienso (opinión) que el navegador no es el problema. En la consola del navegador (inspector) se puede observar como el navegador intenta abrir websocket contra AutoFirma y no puede, y el diálogo de error lo presenta AutoFirma, no el navegador. Teoría loca: coincide que me dejase de funcionar tras instalar dnie (paquete debian descargado de la web de la policía).
> 
> Confirmo error y solución:
> 
> Autofirma 1.8.3 Ubuntu 24.04.1 LTS
> 
> ```
> sudo apt remove --purge autofirma
> sudo dpkg -i AutoFirma_1_8_3.deb
> ```

Esto me ha funcionado. Gracias!

**Comment by sgilfra** [comment]
Mismo error y misma solución con Debian 13 y autofirma_1.9

```
sudo apt remove --purge autofirma
sudo dpkg -i autoFirma_1.9.deb
```

**Comment by isidroas** [comment]
Esto sigue pasando

Ya hay un fix en #387 pero no se ha aceptado todavia

**Comment by jponf** [comment]
A mí me salía el error en macOS. Pero el problema ha resultado ser de permisos y podría ser el mismo en Linux:

En los logs `$HOME/.afirma/AUTOFIRMA.afirma.log.xml` encontré otro error justo antes del SAF_45 que sale en la interficie de usuario, quitando los tags del XML sería el siguiente:

> 18:07:35.886 [INFO]
>  Tratamos de abrir el socket en el puerto: 63117
> 18:07:35.893 [WARNING]
>  No se ha podido abrir un socket en el puerto: 63117
> Exception: java.security.KeyStoreException: No se encuentra el almacen para el cifrado de la comunicacion SSL
> 18:07:35.893 [SEVERE]
>  No se pudo abrir ninguno de los puertos proporcionados
>  Exception: SocketOperationException: No se ha podido abrir ningun socket. Se aborta la comunicacion.
> 18:11:16.256 [SEVERE]
> Ha ocurrido un error realizando la operación. (SAF_45: No se pudo abrir un socket para la comunicación con la aplicación)

En macOS pude comprobar que no tenía acceso a `~/Library/Application\ Support/AutoFirma` por qué se le había asignado el directorio al usuario `root`:

```shell
drwx------   7 root      staff    224 Oct 30 11:38 AutoFirma
```

Intuyo que los certificados de este directorio son los que usa AutoFirma para abrir un WebSocket seguro:

```
-rwxrwxrwx   1 josep  staff    792 Oct 30 11:38 AutoFirma_ROOT.cer
-rwxrwxrwx   1 josep  staff    803 Oct 30 11:38 autofirma.cer
-rwxrwxrwx   1 josep  staff   3578 Oct 30 11:38 autofirma.pfx
drwxrwxrwx  16 josep  staff    512 May 22  2025 certutil
```

Tras reasignar los permisos a mi usuario:

```shell
sudo chown -R $(whoami):staff ~/Library/Application\ Support/AutoFirma  
```

Autofirma volvió a funcionar usando firefox/edge/chrome/...

No sé a qué directorio correspondería en Linux, pero imagino que será del estilo `~/.config/AutoFirma` o `~/.local/share/AutoFirma`.

¡Suerte!

**Comment by m7z** [comment]
> A mí me salía el error en macOS. Pero el problema ha resultado ser de permisos y podría ser el mismo en Linux:
> 
> En los logs `$HOME/.afirma/AUTOFIRMA.afirma.log.xml` encontré otro error justo antes del SAF_45 que sale en la interficie de usuario, quitando los tags del XML sería el siguiente:
> 
> > 18:07:35.886 [INFO]
> > Tratamos de abrir el socket en el puerto: 63117
> > 18:07:35.893 [WARNING]
> > No se ha podido abrir un socket en el puerto: 63117
> > Exception: java.security.KeyStoreException: No se encuentra el almacen para el cifrado de la comunicacion SSL
> > 18:07:35.893 [SEVERE]
> > No se pudo abrir ninguno de los puertos proporcionados
> > Exception: SocketOperationException: No se ha podido abrir ningun socket. Se aborta la comunicacion.
> > 18:11:16.256 [SEVERE]
> > Ha ocurrido un error realizando la operación. (SAF_45: No se pudo abrir un socket para la comunicación con la aplicación)
> 
> En macOS pude comprobar que no tenía acceso a `~/Library/Application\ Support/AutoFirma` por qué se le había asignado el directorio al usuario `root`:
> 
> drwx------   7 root      staff    224 Oct 30 11:38 AutoFirma
> Intuyo que los certificados de este directorio son los que usa AutoFirma para abrir un WebSocket seguro:
> 
> ```
> -rwxrwxrwx   1 josep  staff    792 Oct 30 11:38 AutoFirma_ROOT.cer
> -rwxrwxrwx   1 josep  staff    803 Oct 30 11:38 autofirma.cer
> -rwxrwxrwx   1 josep  staff   3578 Oct 30 11:38 autofirma.pfx
> drwxrwxrwx  16 josep  staff    512 May 22  2025 certutil
> ```
> 
> Tras reasignar los permisos a mi usuario:
> 
> sudo chown -R $(whoami):staff ~/Library/Application\ Support/AutoFirma  
> Autofirma volvió a funcionar usando firefox/edge/chrome/...
> 
> No sé a qué directorio correspondería en Linux, pero imagino que será del estilo `~/.config/AutoFirma` o `~/.local/share/AutoFirma`.
> 
> ¡Suerte!

macOS Tahoe 26.3 (25D125)
AutoFirma 1.8.4
Java 17.0.9 (64 bits)

The above did not work for me because the user who originally installed AutoFirma system wide is not the user who was running and currently owned these directories hence the permission issue in my case meant that those certificates did not even exist nor I had this directory "~/Library/Application\ Support/AutoFirma" (for some reason I ignore... after reinstall I do have it, see below)

Fix: AutoFirma > Tools (Herramientas) > Restore installation (Restaurar instalación)

The UI shows a final log message inside the window that pops up, "FIN" / "END" (read it) and you're done.

**Comment by i92guboj** [comment]
El problema parece ser que el deb no comprueba que haya una versión de java instalada en el sistema. Quizás no hace falta para usar la aplicación, pero desde luego parece ser necesaria para el setup inicial de los certificados (al menos los gestionados por nss). Es tan sencillo como añadir un depend al .deb (o al empaquetado que sea, todos tienen mecanismos similares). O mejor aún, dejarse ya de tonterías y firmar en el navegador directamente, porque en el punto en el que te piden autofirma el navegador ya te ha pedido tu certificado 14 veces para acceder a cualquier portal de la administración y aquí autofirma es ya un nivel de complejidad innecesario del todo... 

En todo caso, si: desinstalar, reinstalar. The windows way...
