### ISSUE TITLE
Error últilizando autofirma con certificado FNMT en Mac M2

### ISSUE THREAD

**Issue by palonso** [ctt-gob-es/clienteafirma#380]
Hola!

Estoy intentando firmar un documento con AutoFirma 1.8.2 y Java 17.0.6 en Mac M2 Sonoma 14.3.
Mi certificado está en un archivo .p12 expedido por la FNMT.

El código de error es el siguiente:

```
es.gob.afirma.core.AOException: Error al generar la firma PKCS#1 de la firma PAdES: es.gob.afirma.core.AOException: Error al verificar el PKCS#1 de la firma
      at es.gob.afirma.signers.pades.AOPDFSigner.sign(AOPDFSigner.java:229)
      at es.gob.afirma.standalone.ui.SignPanelSignTask.signData(SignPanelSignTask.java:554)
      at es.gob.afirma.standalone.ui.SignPanelSignTask.doSignature(SignPanelSignTask.java:314)
      at es.gob.afirma.standalone.ui.SignPanelSignTask.doInBackground(SignPanelSignTask.java:133)
      at es.gob.afirma.standalone.ui.SignPanelSignTask.doInBackground(SignPanelSignTask.java:73)
      at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
      at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
      at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.base/java.lang.Thread.run(Unknown Source)
Caused by: es.gob.afirma.core.AOException: Error al verificar el PKCS#1 de la firma
      at es.gob.afirma.core.signers.AOPkcs1Signer.sign(AOPkcs1Signer.java:124)
      at es.gob.afirma.signers.pades.AOPDFSigner.sign(AOPDFSigner.java:217)
      ... 10 more
Caused by: es.gob.afirma.core.AOException: El PKCS#1 de firma obtenido no se genero con el certificado indicado
      at es.gob.afirma.core.signers.AOPkcs1Signer.sign(AOPkcs1Signer.java:120)
      ... 11 more
```

También obtengo un error al intentar añadir el certificado al llavero de Mac como se explica [aquí](https://www.sede.fnmt.gob.es/en/preguntas-frecuentes/android-mac/-/asset_publisher/1RphW9IeUoAH/content/1380-como-puedo-importar-mi-certificado-desde-el-llavero-de-mac-?_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_1RphW9IeUoAH_assetEntryId=10529353&_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_1RphW9IeUoAH_redirect=https%3A%2F%2Fwww.sede.fnmt.gob.es%2Fen%2Fpreguntas-frecuentes%2Fandroid-mac%3Fp_p_id%3Dcom_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_1RphW9IeUoAH%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_1RphW9IeUoAH_cur%3D0%26p_r_p_resetCur%3Dfalse%26_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_1RphW9IeUoAH_assetEntryId%3D10529353).

Alguna posible solución?

**Comment by ogarcia** [comment]
@palonso prueba con Java 11, con Java 17 no funciona
