### ISSUE TITLE
Autofirma arroja excepción al iniciar proceso de firma con el Tesoro Público

### ISSUE THREAD

**Issue by wyan** [ctt-gob-es/clienteafirma#402]
Desde un Apple Macbook Air M1 (modelo de 2021) con macOS 14.5 Sonoma.

Utilizando Autofirma 1.8.3 desde la página enlazada por el Tesoro Público (https://firmaelectronica.gob.es/Home/Descargas.html)

Intentando firmar el alta de una nueva cuenta del Banco de España para realizar suscripción del Tesoro Público, Autofirma inicia, y pasados unos segundos sin abrir ninguna ventana arroja la siguiente excepción antes de cerrar:

```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
      at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
      at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
      at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
      at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
      at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
      at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
      at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
      at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
      at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
      at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
      at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
      at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
      at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
      at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
      at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
      at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
      at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
      at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
      at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
      at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
      at es.gob.afirma.core.misc.http.UrlHttpManagerImpl.readUrl(UrlHttpManagerImpl.java:254)
      at es.gob.afirma.core.misc.http.UrlHttpManagerImpl.readUrl(UrlHttpManagerImpl.java:128)
      at es.gob.afirma.core.misc.http.UrlHttpManagerImpl.readUrl(UrlHttpManagerImpl.java:99)
      at es.gob.afirma.standalone.HttpManager.readUrl(HttpManager.java:37)
      at es.gob.afirma.standalone.protocol.IntermediateServerUtil.send(IntermediateServerUtil.java:82)
      at es.gob.afirma.standalone.protocol.IntermediateServerUtil.retrieveData(IntermediateServerUtil.java:72)
      at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncherUtil.getDataFromRetrieveServlet(ProtocolInvocationLauncherUtil.java:64)
      at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher.launch(ProtocolInvocationLauncher.java:665)
      at es.gob.afirma.standalone.protocol.ProtocolInvocationLauncher.launch(ProtocolInvocationLauncher.java:138)
      at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:691)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
      at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
      at java.base/sun.security.validator.Validator.validate(Unknown Source)
      at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
      at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
      ... 27 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
      at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
      at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
      ... 32 more
```

**Comment by jmmut** [comment]
A mí me daba el mismo error y el workaround de este comentario me funcionó (desactivar que solo permita conectarse a sitios seguros) https://github.com/ctt-gob-es/clienteafirma/issues/321#issuecomment-1790382794 .

**Comment by wyan** [comment]
En ese caso casi que prefiero mantener mi solución actual (usar una versión anterior de AutoFirma). Desactivar la seguridad me parece una opción francamente preocupante...

**Comment by ivan-zaera** [comment]
> En ese caso casi que prefiero mantener mi solución actual (usar una versión anterior de AutoFirma). Desactivar la seguridad me parece una opción francamente preocupante...

@wyan por si te sirve, esta solución es "algo más segura" -> https://github.com/ctt-gob-es/clienteafirma/issues/321#issuecomment-2399080748

Tenemos una Administración Pública que no nos la merecemos... :troll:

**Comment by wyan** [comment]
Al volver a actualizar a la última versión (porque la versión antigua dejó de funcionar), ahora no me da el fallo ¯\_(ツ)_/¯
