### ISSUE TITLE
NullPointer Exception en Kubuntu 18.04

### ISSUE THREAD

**Issue by rbejar** [ctt-gob-es/clienteafirma#74]
Hola,

lanzando AutoFirma 1.6.2 en Kubuntu 18.04 recién instalado a partir de su .deb desde línea de comandos me da esta excepción:
```
...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.getSystemNSSLibDir(MozillaKeyStoreUtilities.java:246)
        at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:690)
        at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:111)
        at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:58)
        at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:68)
        at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:488)
        at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:519)
        at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:116)
        at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:571)
Caused by: java.lang.NullPointerException
        at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.searchLastFirefoxVersion(MozillaKeyStoreUtilitiesUnix.java:99)
        at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.<clinit>(MozillaKeyStoreUtilitiesUnix.java:32)
        ... 9 more
```
Revisando un poco el código en este repositorio, he llegado a la conclusión tentativa de que se debe a que la clase `MozillaKeyStoreUtilitiesUnix` está tratando de listar los archivos de mi directorio `/opt` (línea 97) y que al ir a recorrer el String[] que devuelve (línea 99), este es null y por eso falla. He mirado los permisos en este directorio y son raritos, concretamente son 0711 para el directorio `.` , lo que implica que solo el propietario (root) puede listar ese directorio. He probado tanto a lanzar AutoFirma con sudo como a cambiar los permisos de /opt y a lanzar AutoFirma con mi usuario normal, y en ambos casos se abre aparantemente bien, así que parece que el problema serían los permisos de ese directorio (que no creo haber modificado yo, así que vendrán así en la instalación del SO).

La documentación del `File.list()` señala que devuelve null si se produce un error de entrada/salida, así que supongo que comprobar que el valor devuelto no es null antes de intentar recorrerlo sería suficiente para solucionar el problema.

Saludos,

P.D. Por completitud, esta es la salida completa de la ejecución de AutoFirma por consola:
```
feb 04, 2019 5:49:45 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFORMACIÓN: Las conexiones para protocolo 'http' son por defecto de tipo: DIRECT
feb 04, 2019 5:49:45 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFORMACIÓN: Las conexiones para protocolo 'https' son por defecto de tipo: DIRECT
feb 04, 2019 5:49:45 PM es.gob.afirma.standalone.ProxyUtil setProxySettings
INFORMACIÓN: No se usara Proxy para las conexiones de red
feb 04, 2019 5:49:45 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: No se buscaran nuevas versiones de la aplicacion
feb 04, 2019 5:49:45 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFORMACIÓN: Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 4.15.0-45-generic
Version de Java: 1.8.0_201
Arquitectura del JRE: 64
Java Vendor: Oracle Corporation
Localizacion por defecto: es_ES
Tamano actual en memoria: 479MB
Tamano maximo de memoria: 7097MB
Memoria actualmente libre: 402MB
feb 04, 2019 5:49:45 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Apertura como herramienta de escritorio
feb 04, 2019 5:49:46 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Se intenta una precarga temprana de NSS
Exception in thread "main" java.lang.ExceptionInInitializerError
        at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.getSystemNSSLibDir(MozillaKeyStoreUtilities.java:246)
        at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:690)
        at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:111)
        at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:58)
        at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:68)
        at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:488)
        at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:519)
        at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:116)
        at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:571)
Caused by: java.lang.NullPointerException
        at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.searchLastFirefoxVersion(MozillaKeyStoreUtilitiesUnix.java:99)
        at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.<clinit>(MozillaKeyStoreUtilitiesUnix.java:32)
        ... 9 more
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by Gamuci** [comment]
Se ha agregado la comprobación. Gracias por el aviso.
